"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "update_workspace_safety",
            "description": "UpdateWorkspace only permitted for users in Role-A (ceiling: must be in Role-A)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_update.cedar"),
        },
        {
            "name": "delete_workspace_safety",
            "description": "DeleteWorkspace only permitted for users in Role-A",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_delete.cedar"),
        },
        {
            "name": "read_workspace_safety",
            "description": "ReadWorkspace only permitted for users in Role-A or Role-B",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_read.cedar"),
        },
        {
            "name": "sensitivity_role_a_forbid",
            "description": "Role-A actions must be denied when workspace sensitivity > 3",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_update_sensitivity.cedar"),
        },
        {
            "name": "sensitivity_role_a_forbid_delete",
            "description": "DeleteWorkspace must be denied when workspace sensitivity > 3",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_delete_sensitivity.cedar"),
        },
        {
            "name": "sensitivity_role_a_forbid_read",
            "description": "ReadWorkspace via Role-A must be denied when workspace sensitivity > 3 (and user is only in Role-A)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_read_sensitivity.cedar"),
        },
        {
            "name": "floor_role_a_update",
            "description": "A Role-A user with ALL wildcard tags and sensitivity <= 3 MUST be able to UpdateWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_role_a_update.cedar"),
        },
        {
            "name": "floor_role_a_delete",
            "description": "A Role-A user with ALL wildcard tags and sensitivity <= 3 MUST be able to DeleteWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_role_a_delete.cedar"),
        },
        {
            "name": "floor_role_b_read",
            "description": "A Role-B user with ALL wildcard tags and sensitivity <= 1 MUST be able to ReadWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_role_b_read.cedar"),
        },
        {
            "name": "liveness_update",
            "description": "UpdateWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_delete",
            "description": "DeleteWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_read",
            "description": "ReadWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
        },
    ]
