"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_reservation_safety",
            "description": "viewReservation only allowed if resource is in viewer, member, or admin permission sets (franchise/hotel/property level)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "update_reservation_safety",
            "description": "updateReservation only allowed if resource is in member or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grant_access_reservation_safety",
            "description": "grantAccessReservation only allowed if resource is in admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "create_reservation_safety",
            "description": "createReservation only allowed if resource is in member or admin permission sets, property not premium or loyaltyTier >= 3, and not under renovation unless admin",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "view_property_safety",
            "description": "viewProperty only allowed if resource is in viewer, member, or admin permission sets at any level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "update_property_safety",
            "description": "updateProperty only allowed if resource is in member or admin permission sets at any level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grant_access_property_safety",
            "description": "grantAccessProperty only allowed if resource is in admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "view_hotel_safety",
            "description": "viewHotel only allowed via franchise or hotel level viewer, member, or admin sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "update_hotel_safety",
            "description": "updateHotel only allowed via franchise or hotel level member or admin sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "grant_access_hotel_safety",
            "description": "grantAccessHotel only allowed via franchise or hotel level admin sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "create_property_safety",
            "description": "createProperty only allowed via franchise or hotel level member or admin sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "create_hotel_safety",
            "description": "createHotel only allowed via franchise or hotel level member or admin sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "view_franchise_safety",
            "description": "viewFranchise only allowed if franchise is in viewer, member, or admin franchise sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewFranchise\"",
            "resource_type": "Franchise",
            "reference_path": os.path.join(REFS, "ceiling_viewFranchise.cedar"),
        },
        {
            "name": "update_franchise_safety",
            "description": "updateFranchise only allowed if franchise is in member or admin franchise sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateFranchise\"",
            "resource_type": "Franchise",
            "reference_path": os.path.join(REFS, "ceiling_updateFranchise.cedar"),
        },
        {
            "name": "grant_access_franchise_safety",
            "description": "grantAccessFranchise only allowed if franchise is in franchiseAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessFranchise\"",
            "resource_type": "Franchise",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessFranchise.cedar"),
        },
        {
            "name": "renovation_lock_enforced",
            "description": "createReservation is forbidden on properties under renovation for non-admin users",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "loyalty_tier_enforced",
            "description": "createReservation is forbidden on premium properties for users with loyaltyTier < 3",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "floor_viewer_view_reservation",
            "description": "A viewer with property-level viewer permissions MUST be able to viewReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewReservation_viewer.cedar"),
        },
        {
            "name": "floor_member_update_reservation",
            "description": "A member with property-level member permissions MUST be able to updateReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_updateReservation_member.cedar"),
        },
        {
            "name": "floor_admin_grant_reservation",
            "description": "An admin with property-level admin permissions MUST be able to grantAccessReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_grantAccessReservation_admin.cedar"),
        },
        {
            "name": "floor_member_create_reservation",
            "description": "A member with property-level member permissions MUST be able to createReservation on non-renovation non-premium property",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_createReservation_member.cedar"),
        },
        {
            "name": "floor_admin_create_reservation_renovation",
            "description": "An admin MUST be able to createReservation on a renovating non-premium property (admin bypass)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_createReservation_admin_renovation.cedar"),
        },
        {
            "name": "floor_franchise_admin_grant_franchise",
            "description": "A franchise admin MUST be able to grantAccessFranchise",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessFranchise\"",
            "resource_type": "Franchise",
            "floor_path": os.path.join(REFS, "floor_grantAccessFranchise_admin.cedar"),
        },
        {
            "name": "liveness_view_reservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_update_reservation",
            "description": "updateReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_create_reservation",
            "description": "createReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grant_access_reservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_view_property",
            "description": "viewProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grant_access_franchise",
            "description": "grantAccessFranchise is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessFranchise\"",
            "resource_type": "Franchise",
        },
    ]
