"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View access is bounded: only ClinicalResearcher (clearance>3, not HighlyRestricted) or PrincipalInvestigator (riskScore<20, compliant device), on active projects, with department match or GlobalAuditor, and compliant device for HighlyRestricted",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit access is bounded: only ClinicalResearcher (clearance>3, not HighlyRestricted) or PrincipalInvestigator (riskScore<20, compliant device), on active projects, with department match or GlobalAuditor, and compliant device for HighlyRestricted",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "active_project_gate_view",
            "description": "View is only possible when projectStatus is Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_project_view.cedar"),
        },
        {
            "name": "active_project_gate_edit",
            "description": "Edit is only possible when projectStatus is Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_project_edit.cedar"),
        },
        {
            "name": "cross_dept_block_view",
            "description": "View is forbidden when department != projectManagingDepartment unless GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_dept_match_view.cedar"),
        },
        {
            "name": "cross_dept_block_edit",
            "description": "Edit is forbidden when department != projectManagingDepartment unless GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_dept_match_edit.cedar"),
        },
        {
            "name": "device_compliance_highly_restricted_view",
            "description": "View of HighlyRestricted documents requires compliant device, no exceptions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_device_compliance_view.cedar"),
        },
        {
            "name": "device_compliance_highly_restricted_edit",
            "description": "Edit of HighlyRestricted documents requires compliant device, no exceptions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_device_compliance_edit.cedar"),
        },
        {
            "name": "clinical_researcher_view_floor",
            "description": "ClinicalResearcher with clearance>3, non-HighlyRestricted doc, active project, matching dept, compliant device, low risk score MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_clinical_researcher_view.cedar"),
        },
        {
            "name": "principal_investigator_view_floor",
            "description": "PrincipalInvestigator with riskScore<20, compliant device, active project, matching dept, non-HighlyRestricted doc MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "clinical_researcher_edit_floor",
            "description": "ClinicalResearcher with clearance>3, non-HighlyRestricted doc, active project, matching dept, compliant device, low risk score MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_clinical_researcher_edit.cedar"),
        },
        {
            "name": "principal_investigator_edit_floor",
            "description": "PrincipalInvestigator with riskScore<20, compliant device, active project, matching dept, non-HighlyRestricted doc MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_edit.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
    ]
