"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View is only allowed when projectStatus is Active, user is in one of the three permitted roles, and role-specific constraints are met (ClinicalResearcher: clearance>3 & not HighlyRestricted; PI: riskScore<20 & compliant device; SponsorRep: Phase-3 only)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit is only allowed when projectStatus is Active, user is ClinicalResearcher or PrincipalInvestigator (not SponsorRep), and role-specific constraints are met",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "cross_dept_block_view_safety",
            "description": "View is forbidden when department != projectManagingDepartment unless user is GlobalAuditor or SponsorRepresentative",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_view.cedar"),
        },
        {
            "name": "cross_dept_block_edit_safety",
            "description": "Edit is forbidden when department != projectManagingDepartment unless user is GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_edit.cedar"),
        },
        {
            "name": "sponsor_no_edit_safety",
            "description": "A SponsorRepresentative who is not also in ClinicalResearcher or PrincipalInvestigator roles should never be granted Edit access solely via SponsorRepresentative path. Ceiling: Edit requires CR or PI membership.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_sponsor_no_edit.cedar"),
        },
        {
            "name": "floor_clinical_researcher_view",
            "description": "A ClinicalResearcher with clearanceLevel>3, matching department, active project, non-HighlyRestricted doc, compliant context MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_clinical_researcher_view.cedar"),
        },
        {
            "name": "floor_pi_view",
            "description": "A PrincipalInvestigator with riskScore<20, compliant device, matching department, active project MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "floor_sponsor_view",
            "description": "A SponsorRepresentative viewing a Phase-3 doc in an active project MUST be allowed (regardless of department)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_sponsor_view.cedar"),
        },
        {
            "name": "floor_clinical_researcher_edit",
            "description": "A ClinicalResearcher with clearanceLevel>3, matching department, active project, non-HighlyRestricted doc MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_clinical_researcher_edit.cedar"),
        },
        {
            "name": "floor_pi_edit",
            "description": "A PrincipalInvestigator with riskScore<20, compliant device, matching department, active project MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_edit.cedar"),
        },
        {
            "name": "floor_global_auditor_cross_dept_view",
            "description": "A GlobalAuditor who is also a ClinicalResearcher (clearance>3, non-HighlyRestricted, active project) MUST be able to View even across departments",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_global_auditor_cross_dept_view.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
    ]
