"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "pull_safety",
            "description": "Pull access only for users who are readers of the repository",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_pull.cedar"),
        },
        {
            "name": "fork_safety",
            "description": "Fork access only for users who are readers of the repository",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_fork.cedar"),
        },
        {
            "name": "push_safety",
            "description": "Push access only for writers, and blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_push.cedar"),
        },
        {
            "name": "edit_issue_safety",
            "description": "Edit issue only if (reader AND reporter) OR writer of the repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_edit_issue.cedar"),
        },
        {
            "name": "delete_issue_safety",
            "description": "Delete issue only if (reader AND reporter) OR maintainer of the repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_delete_issue.cedar"),
        },
        {
            "name": "assign_issue_safety",
            "description": "Assign issue only for triagers of the repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_assign_issue.cedar"),
        },
        {
            "name": "add_reader_safety",
            "description": "Add reader only if admin, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_reader.cedar"),
        },
        {
            "name": "add_writer_safety",
            "description": "Add writer only if admin, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_writer.cedar"),
        },
        {
            "name": "add_maintainer_safety",
            "description": "Add maintainer only if admin, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_maintainer.cedar"),
        },
        {
            "name": "add_admin_safety",
            "description": "Add admin only if admin, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_admin.cedar"),
        },
        {
            "name": "add_triager_safety",
            "description": "Add triager only if admin, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_triager.cedar"),
        },
        {
            "name": "merge_pr_safety",
            "description": "Merge PR only for writers/maintainers/admins of the PR's repo, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"merge_pr\"",
            "resource_type": "PullRequest",
            "reference_path": os.path.join(REFS, "ceiling_merge_pr.cedar"),
        },
        {
            "name": "approve_pr_safety",
            "description": "Approve PR only for readers of the PR's repo, and not the PR author",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"approve_pr\"",
            "resource_type": "PullRequest",
            "reference_path": os.path.join(REFS, "ceiling_approve_pr.cedar"),
        },
        {
            "name": "reader_pull_floor",
            "description": "Readers MUST be able to pull from the repository",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_pull.cedar"),
        },
        {
            "name": "reader_fork_floor",
            "description": "Readers MUST be able to fork the repository",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_fork.cedar"),
        },
        {
            "name": "writer_push_floor",
            "description": "Writers MUST be able to push to non-archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_writer_push.cedar"),
        },
        {
            "name": "writer_edit_issue_floor",
            "description": "Writers MUST be able to edit any issue in the repo",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_writer_edit_issue.cedar"),
        },
        {
            "name": "reporter_reader_edit_issue_floor",
            "description": "Readers who are the reporter MUST be able to edit their own issue",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_reporter_edit_issue.cedar"),
        },
        {
            "name": "reporter_reader_delete_issue_floor",
            "description": "Readers who are the reporter MUST be able to delete their own issue",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_reporter_delete_issue.cedar"),
        },
        {
            "name": "maintainer_delete_issue_floor",
            "description": "Maintainers MUST be able to delete any issue in the repo",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_maintainer_delete_issue.cedar"),
        },
        {
            "name": "triager_assign_issue_floor",
            "description": "Triagers MUST be able to assign issues",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_triager_assign_issue.cedar"),
        },
        {
            "name": "admin_add_reader_floor",
            "description": "Admins MUST be able to add readers to non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_reader.cedar"),
        },
        {
            "name": "pull_archived_floor",
            "description": "Readers MUST be able to pull from archived repositories (read ops unaffected)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_pull_archived.cedar"),
        },
        {
            "name": "approve_pr_reader_floor",
            "description": "Readers (non-authors) MUST be able to approve PRs",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"approve_pr\"",
            "resource_type": "PullRequest",
            "floor_path": os.path.join(REFS, "floor_approve_pr.cedar"),
        },
        {
            "name": "merge_pr_writer_floor",
            "description": "Writers MUST be able to merge PRs on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"merge_pr\"",
            "resource_type": "PullRequest",
            "floor_path": os.path.join(REFS, "floor_merge_pr.cedar"),
        },
        {
            "name": "liveness_pull",
            "description": "Pull policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_push",
            "description": "Push policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_fork",
            "description": "Fork policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_edit_issue",
            "description": "Edit issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_delete_issue",
            "description": "Delete issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_assign_issue",
            "description": "Assign issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_add_reader",
            "description": "Add reader policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_merge_pr",
            "description": "Merge PR policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"merge_pr\"",
            "resource_type": "PullRequest",
        },
        {
            "name": "liveness_approve_pr",
            "description": "Approve PR policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"approve_pr\"",
            "resource_type": "PullRequest",
        },
    ]
