"""Verification plan for twenty_action_workflow."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")

def get_checks():
    return [
        {"name": "ceiling_request", "description": "request ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"request"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_request.cedar")},
        {"name": "ceiling_review", "description": "review ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"review"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_review.cedar")},
        {"name": "ceiling_approve", "description": "approve ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"approve"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_approve.cedar")},
        {"name": "ceiling_reject", "description": "reject ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"reject"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_reject.cedar")},
        {"name": "ceiling_escalate", "description": "escalate ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"escalate"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_escalate.cedar")},
        {"name": "ceiling_delegate", "description": "delegate ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"delegate"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_delegate.cedar")},
        {"name": "ceiling_cancel", "description": "cancel ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"cancel"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_cancel.cedar")},
        {"name": "ceiling_resubmit", "description": "resubmit ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"resubmit"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_resubmit.cedar")},
        {"name": "ceiling_audit", "description": "audit ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"audit"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_audit.cedar")},
        {"name": "ceiling_close", "description": "close ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"close"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_close.cedar")},
        {"name": "ceiling_reopen", "description": "reopen ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"reopen"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_reopen.cedar")},
        {"name": "ceiling_archive", "description": "archive ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"archive"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_archive.cedar")},
        {"name": "ceiling_export", "description": "export ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"export"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_export.cedar")},
        {"name": "ceiling_sign", "description": "sign ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"sign"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_sign.cedar")},
        {"name": "ceiling_countersign", "description": "countersign ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"countersign"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_countersign.cedar")},
        {"name": "ceiling_annotate", "description": "annotate ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"annotate"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_annotate.cedar")},
        {"name": "ceiling_comment", "description": "comment ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"comment"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_comment.cedar")},
        {"name": "ceiling_notify", "description": "notify ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"notify"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_notify.cedar")},
        {"name": "ceiling_cc", "description": "cc ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"cc"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_cc.cedar")},
        {"name": "ceiling_bcc", "description": "bcc ceiling", "type": "implies", "principal_type": "User", "action": 'Action::"bcc"', "resource_type": "Document", "reference_path": os.path.join(REFS, "ceiling_bcc.cedar")},
        {"name": "floor_requester_request", "description": "requester request", "type": "floor", "principal_type": "User", "action": 'Action::"request"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_requester_request.cedar")},
        {"name": "floor_reviewer_review", "description": "reviewer review", "type": "floor", "principal_type": "User", "action": 'Action::"review"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_reviewer_review.cedar")},
        {"name": "floor_approver_approve", "description": "approver approve", "type": "floor", "principal_type": "User", "action": 'Action::"approve"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_approver_approve.cedar")},
        {"name": "floor_approver_reject", "description": "approver reject", "type": "floor", "principal_type": "User", "action": 'Action::"reject"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_approver_reject.cedar")},
        {"name": "floor_requester_escalate", "description": "requester escalate", "type": "floor", "principal_type": "User", "action": 'Action::"escalate"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_requester_escalate.cedar")},
        {"name": "floor_approver_delegate", "description": "approver delegate", "type": "floor", "principal_type": "User", "action": 'Action::"delegate"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_approver_delegate.cedar")},
        {"name": "floor_requester_cancel", "description": "requester cancel", "type": "floor", "principal_type": "User", "action": 'Action::"cancel"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_requester_cancel.cedar")},
        {"name": "floor_requester_resubmit", "description": "requester resubmit", "type": "floor", "principal_type": "User", "action": 'Action::"resubmit"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_requester_resubmit.cedar")},
        {"name": "floor_auditor_audit", "description": "auditor audit", "type": "floor", "principal_type": "User", "action": 'Action::"audit"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_auditor_audit.cedar")},
        {"name": "floor_manager_close", "description": "manager close", "type": "floor", "principal_type": "User", "action": 'Action::"close"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_manager_close.cedar")},
        {"name": "floor_manager_reopen", "description": "manager reopen", "type": "floor", "principal_type": "User", "action": 'Action::"reopen"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_manager_reopen.cedar")},
        {"name": "floor_manager_archive", "description": "manager archive", "type": "floor", "principal_type": "User", "action": 'Action::"archive"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_manager_archive.cedar")},
        {"name": "floor_auditor_export", "description": "auditor export", "type": "floor", "principal_type": "User", "action": 'Action::"export"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_auditor_export.cedar")},
        {"name": "floor_approver_sign", "description": "approver sign", "type": "floor", "principal_type": "User", "action": 'Action::"sign"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_approver_sign.cedar")},
        {"name": "floor_manager_countersign", "description": "manager countersign", "type": "floor", "principal_type": "User", "action": 'Action::"countersign"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_manager_countersign.cedar")},
        {"name": "floor_requester_annotate", "description": "requester annotate", "type": "floor", "principal_type": "User", "action": 'Action::"annotate"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_requester_annotate.cedar")},
        {"name": "floor_manager_notify", "description": "manager notify", "type": "floor", "principal_type": "User", "action": 'Action::"notify"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_manager_notify.cedar")},
        {"name": "floor_requester_cc", "description": "requester cc", "type": "floor", "principal_type": "User", "action": 'Action::"cc"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_requester_cc.cedar")},
        {"name": "floor_manager_bcc", "description": "manager bcc", "type": "floor", "principal_type": "User", "action": 'Action::"bcc"', "resource_type": "Document", "floor_path": os.path.join(REFS, "floor_manager_bcc.cedar")},
        {"name": "liveness_request", "description": "request liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"request"', "resource_type": "Document"},
        {"name": "liveness_review", "description": "review liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"review"', "resource_type": "Document"},
        {"name": "liveness_approve", "description": "approve liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"approve"', "resource_type": "Document"},
        {"name": "liveness_reject", "description": "reject liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"reject"', "resource_type": "Document"},
        {"name": "liveness_escalate", "description": "escalate liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"escalate"', "resource_type": "Document"},
        {"name": "liveness_delegate", "description": "delegate liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"delegate"', "resource_type": "Document"},
        {"name": "liveness_cancel", "description": "cancel liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"cancel"', "resource_type": "Document"},
        {"name": "liveness_resubmit", "description": "resubmit liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"resubmit"', "resource_type": "Document"},
        {"name": "liveness_audit", "description": "audit liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"audit"', "resource_type": "Document"},
        {"name": "liveness_close", "description": "close liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"close"', "resource_type": "Document"},
        {"name": "liveness_reopen", "description": "reopen liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"reopen"', "resource_type": "Document"},
        {"name": "liveness_archive", "description": "archive liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"archive"', "resource_type": "Document"},
        {"name": "liveness_export", "description": "export liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"export"', "resource_type": "Document"},
        {"name": "liveness_sign", "description": "sign liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"sign"', "resource_type": "Document"},
        {"name": "liveness_countersign", "description": "countersign liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"countersign"', "resource_type": "Document"},
        {"name": "liveness_annotate", "description": "annotate liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"annotate"', "resource_type": "Document"},
        {"name": "liveness_comment", "description": "comment liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"comment"', "resource_type": "Document"},
        {"name": "liveness_notify", "description": "notify liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"notify"', "resource_type": "Document"},
        {"name": "liveness_cc", "description": "cc liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"cc"', "resource_type": "Document"},
        {"name": "liveness_bcc", "description": "bcc liveness", "type": "always-denies-liveness", "principal_type": "User", "action": 'Action::"bcc"', "resource_type": "Document"},
    ]
