"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View is only permitted when projectStatus is Active, user is in ClinicalResearcher or PrincipalInvestigator role with respective constraints, and department matches projectManagingDepartment",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit is only permitted when projectStatus is Active, user is in ClinicalResearcher or PrincipalInvestigator role with respective constraints, and department matches projectManagingDepartment",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "cross_department_block_view",
            "description": "View is always denied when user department does not match document projectManagingDepartment",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_dept_match_view.cedar"),
        },
        {
            "name": "cross_department_block_edit",
            "description": "Edit is always denied when user department does not match document projectManagingDepartment",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_dept_match_edit.cedar"),
        },
        {
            "name": "active_project_gate_view",
            "description": "View is only allowed when projectStatus is Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_view.cedar"),
        },
        {
            "name": "active_project_gate_edit",
            "description": "Edit is only allowed when projectStatus is Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_edit.cedar"),
        },
        {
            "name": "researcher_view_floor",
            "description": "A ClinicalResearcher with clearanceLevel > 3, matching department, Active project, non-HighlyRestricted doc MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_researcher_view.cedar"),
        },
        {
            "name": "researcher_edit_floor",
            "description": "A ClinicalResearcher with clearanceLevel > 3, matching department, Active project, non-HighlyRestricted doc MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_researcher_edit.cedar"),
        },
        {
            "name": "pi_view_floor",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, Active project MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "pi_edit_floor",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, Active project MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_edit.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
    ]
