"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View access is only permitted when: project is Active, user is in CR or PI role, CR conditions (clearance>3, not HighlyRestricted) or PI conditions (riskScore<20, compliant device), and department matches or user is GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit access is only permitted under the same conditions as View: Active project, CR or PI role with respective conditions, department match or GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "cross_department_deny_view",
            "description": "View is denied when user department != document projectManagingDepartment and user is not a GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_dept.cedar"),
        },
        {
            "name": "cross_department_deny_edit",
            "description": "Edit is denied when user department != document projectManagingDepartment and user is not a GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_dept.cedar"),
        },
        {
            "name": "inactive_project_deny_view",
            "description": "View is never permitted when project status is not Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_active.cedar"),
        },
        {
            "name": "inactive_project_deny_edit",
            "description": "Edit is never permitted when project status is not Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_active.cedar"),
        },
        {
            "name": "floor_cr_view",
            "description": "A ClinicalResearcher with clearance>3, same department, Active project, non-HighlyRestricted doc MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_view.cedar"),
        },
        {
            "name": "floor_cr_edit",
            "description": "A ClinicalResearcher with clearance>3, same department, Active project, non-HighlyRestricted doc MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_edit.cedar"),
        },
        {
            "name": "floor_pi_view",
            "description": "A PrincipalInvestigator with same department, Active project, compliant device, riskScore<20 MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "floor_pi_edit",
            "description": "A PrincipalInvestigator with same department, Active project, compliant device, riskScore<20 MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_edit.cedar"),
        },
        {
            "name": "floor_auditor_cross_dept_view",
            "description": "A GlobalAuditor+ClinicalResearcher with clearance>3, Active project, non-HighlyRestricted doc, different department MUST still be able to View (auditor loophole)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_auditor_cross_dept_view.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
    ]
