"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "owner_view_safety",
            "description": "ViewDocument is only allowed for owner or viewACL members (authenticated, not blocked)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document.cedar"),
        },
        {
            "name": "owner_modify_safety",
            "description": "ModifyDocument is only allowed for owner or modifyACL members (authenticated, not blocked)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_document.cedar"),
        },
        {
            "name": "delete_document_safety",
            "description": "DeleteDocument is only allowed for owner or manageACL members (authenticated)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete_document.cedar"),
        },
        {
            "name": "edit_is_private_safety",
            "description": "EditIsPrivate is only allowed for owner or manageACL members (authenticated)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "edit_public_access_safety",
            "description": "EditPublicAccess is only allowed for owner or manageACL members (authenticated)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "add_to_share_acl_safety",
            "description": "AddToShareACL is only allowed for owner or manageACL members (authenticated)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "delete_group_safety",
            "description": "DeleteGroup is only allowed for group owner (authenticated)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "modify_group_safety",
            "description": "ModifyGroup is only allowed for group owner (authenticated)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "auth_required_view",
            "description": "ViewDocument must be denied when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_view.cedar"),
        },
        {
            "name": "auth_required_modify",
            "description": "ModifyDocument must be denied when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_modify.cedar"),
        },
        {
            "name": "auth_required_delete",
            "description": "DeleteDocument must be denied when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_delete.cedar"),
        },
        {
            "name": "auth_required_add_share",
            "description": "AddToShareACL must be denied when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_add_share.cedar"),
        },
        {
            "name": "auth_required_delete_group",
            "description": "DeleteGroup must be denied when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_auth_delete_group.cedar"),
        },
        {
            "name": "auth_required_modify_group",
            "description": "ModifyGroup must be denied when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_auth_modify_group.cedar"),
        },
        {
            "name": "blocking_view_safety",
            "description": "ViewDocument must be denied when principal is in owner's blocked set or owner is in principal's blocked set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_blocking_view.cedar"),
        },
        {
            "name": "blocking_modify_safety",
            "description": "ModifyDocument must be denied when principal is in owner's blocked set or owner is in principal's blocked set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_blocking_modify.cedar"),
        },
        {
            "name": "owner_view_floor",
            "description": "Owner MUST be able to ViewDocument when authenticated and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view.cedar"),
        },
        {
            "name": "owner_modify_floor",
            "description": "Owner MUST be able to ModifyDocument when authenticated and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify.cedar"),
        },
        {
            "name": "owner_delete_floor",
            "description": "Owner MUST be able to DeleteDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete.cedar"),
        },
        {
            "name": "owner_add_share_floor",
            "description": "Owner MUST be able to AddToShareACL when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_add_share.cedar"),
        },
        {
            "name": "view_acl_floor",
            "description": "ViewACL members MUST be able to ViewDocument when authenticated and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl.cedar"),
        },
        {
            "name": "modify_acl_floor",
            "description": "ModifyACL members MUST be able to ModifyDocument when authenticated and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl.cedar"),
        },
        {
            "name": "manage_acl_delete_floor",
            "description": "ManageACL members MUST be able to DeleteDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_delete.cedar"),
        },
        {
            "name": "manage_acl_add_share_floor",
            "description": "ManageACL members MUST be able to AddToShareACL when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_add_share.cedar"),
        },
        {
            "name": "group_owner_delete_floor",
            "description": "Group owner MUST be able to DeleteGroup when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_delete.cedar"),
        },
        {
            "name": "group_owner_modify_floor",
            "description": "Group owner MUST be able to ModifyGroup when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_modify.cedar"),
        },
        {
            "name": "liveness_view_document",
            "description": "ViewDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document",
            "description": "ModifyDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_modify_group",
            "description": "ModifyGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
        },
    ]
