"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_presentation_ceiling",
            "description": "viewPresentation only if owner, or viewer (any job), or editor (internal only)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_ceiling",
            "description": "duplicatePresentation only if internal job AND (owner or viewer or editor)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_ceiling",
            "description": "editPresentation only if owner or (editor with internal job)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "remove_self_access_presentation_ceiling",
            "description": "removeSelfAccessFromPresentation only if owner, or viewer (any job), or editor (internal)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "grant_view_presentation_ceiling",
            "description": "grantViewAccessToPresentation only if owner or internal editor; if target is customer then principal must be distributor with matching customerId",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewPresentation.cedar"),
        },
        {
            "name": "grant_edit_presentation_ceiling",
            "description": "grantEditAccessToPresentation only if owner or internal editor; target must be internal; if target is customer then principal must be distributor with matching customerId",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditPresentation.cedar"),
        },
        {
            "name": "view_template_ceiling",
            "description": "viewTemplate only if owner, or viewer (any job), or internal editor, or member of viewerMarket, or internal member of editorMarket",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "duplicate_template_ceiling",
            "description": "duplicateTemplate only if owner, or viewer (any job), or internal editor, or member of viewerMarket, or internal member of editorMarket",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "remove_self_template_ceiling",
            "description": "removeSelfAccessFromTemplate only if owner, or internal viewer, or internal editor, or internal member of editorMarket",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfTemplate.cedar"),
        },
        {
            "name": "edit_template_ceiling",
            "description": "editTemplate only if owner or internal editor or internal member of editorMarket",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "remove_others_template_ceiling",
            "description": "removeOthersAccessToTemplate only if owner or internal editor or internal member of editorMarket",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersTemplate.cedar"),
        },
        {
            "name": "grant_view_template_ceiling",
            "description": "grantViewAccessToTemplate only if owner or internal editor or internal editorMarket member; if targetUser is customer then principal must be distributor with matching customerId",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_ceiling",
            "description": "grantEditAccessToTemplate only if owner or internal editor or internal editorMarket member; targetUser must be internal if present; if targetUser is customer then principal must be distributor with matching customerId",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditTemplate.cedar"),
        },
        {
            "name": "owner_prez_floor",
            "description": "Owner MUST be able to editPresentation on their own Presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_owner_editPresentation.cedar"),
        },
        {
            "name": "owner_template_floor",
            "description": "Owner MUST be able to editTemplate on their own Template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_owner_editTemplate.cedar"),
        },
        {
            "name": "internal_viewer_duplicate_prez_floor",
            "description": "Internal viewers MUST be able to duplicatePresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_viewer_duplicatePresentation.cedar"),
        },
        {
            "name": "external_viewer_view_prez_floor",
            "description": "External (non-internal) viewers MUST be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_viewer_viewPresentation.cedar"),
        },
        {
            "name": "internal_editor_edit_prez_floor",
            "description": "Internal editors MUST be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_editor_editPresentation.cedar"),
        },
        {
            "name": "market_viewer_view_template_floor",
            "description": "Users in a viewerMarket MUST be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_market_viewer_viewTemplate.cedar"),
        },
        {
            "name": "internal_editor_market_edit_template_floor",
            "description": "Internal users in an editorMarket MUST be able to editTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_editorMarket_editTemplate.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_duplicatePresentation",
            "description": "duplicatePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantViewPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditTemplate",
            "description": "grantEditAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
        },
    ]
