"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View access is bounded by: active project, correct role (CR or PI), CR constraints (clearance>3, not HighlyRestricted, not Phase-3), PI constraints (riskScore<20, compliant device), and department match (unless GlobalAuditor)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit access is bounded by: active project, correct role (CR or PI), CR constraints (clearance>3, not HighlyRestricted, not Phase-3), PI constraints (riskScore<20, compliant device), and department match (unless GlobalAuditor)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "cross_dept_block_view",
            "description": "View is forbidden when user department != document projectManagingDepartment and user is not a GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_view.cedar"),
        },
        {
            "name": "cross_dept_block_edit",
            "description": "Edit is forbidden when user department != document projectManagingDepartment and user is not a GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_edit.cedar"),
        },
        {
            "name": "phase3_only_pi_view",
            "description": "Phase-3 documents can only be viewed by PrincipalInvestigators (not ClinicalResearchers)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_phase3_view.cedar"),
        },
        {
            "name": "phase3_only_pi_edit",
            "description": "Phase-3 documents can only be edited by PrincipalInvestigators (not ClinicalResearchers)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_phase3_edit.cedar"),
        },
        {
            "name": "inactive_project_block_view",
            "description": "Documents in non-active projects cannot be viewed",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_view.cedar"),
        },
        {
            "name": "inactive_project_block_edit",
            "description": "Documents in non-active projects cannot be edited",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_edit.cedar"),
        },
        {
            "name": "floor_pi_view",
            "description": "A PrincipalInvestigator with matching department, compliant device, low risk score, active project MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "floor_pi_edit",
            "description": "A PrincipalInvestigator with matching department, compliant device, low risk score, active project MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_edit.cedar"),
        },
        {
            "name": "floor_cr_view",
            "description": "A ClinicalResearcher with matching department, clearance>3, non-HighlyRestricted, non-Phase-3, active project MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_view.cedar"),
        },
        {
            "name": "floor_cr_edit",
            "description": "A ClinicalResearcher with matching department, clearance>3, non-HighlyRestricted, non-Phase-3, active project MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_edit.cedar"),
        },
        {
            "name": "floor_auditor_cross_dept_view",
            "description": "A GlobalAuditor+PrincipalInvestigator with compliant device, low risk, active project MUST be able to View even with mismatched department",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_auditor_cross_dept_view.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
    ]
