"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_reservation_safety",
            "description": "viewReservation is only permitted if the user has view, member, or admin role covering the reservation's property/hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "update_reservation_safety",
            "description": "updateReservation is only permitted if the user has member or admin role covering the reservation's property/hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grant_access_reservation_safety",
            "description": "grantAccessReservation is only permitted if the user has admin role covering the reservation's property/hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "create_reservation_safety",
            "description": "createReservation on a Property is only permitted if the user has member or admin role covering that property/hotel for reservations",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "view_property_safety",
            "description": "viewProperty is only permitted if the user has any role (view/member/admin) for any resource type at that property or its hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "update_property_safety",
            "description": "updateProperty is only permitted if the user has member or admin role at that property or its hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grant_access_property_safety",
            "description": "grantAccessProperty is only permitted if the user has admin role at that property or its hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "create_property_safety",
            "description": "createProperty on a Hotel is only permitted if the user has member or admin role at that hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "create_hotel_safety",
            "description": "createHotel on a Hotel is only permitted if the user is admin of that hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "view_hotel_safety",
            "description": "viewHotel is only permitted if the user has any role (view/member/admin) for any resource type at that hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "update_hotel_safety",
            "description": "updateHotel is only permitted if the user has member or admin role at that hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "grant_access_hotel_safety",
            "description": "grantAccessHotel is only permitted if the user is admin at that hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "view_reservation_viewer_floor",
            "description": "A user who is a viewer for reservations at the reservation's property MUST be able to viewReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewReservation_viewer.cedar"),
        },
        {
            "name": "update_reservation_member_floor",
            "description": "A user who is a member for reservations at the reservation's property MUST be able to updateReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_updateReservation_member.cedar"),
        },
        {
            "name": "grant_access_reservation_admin_floor",
            "description": "A user who is a property admin at the reservation's property MUST be able to grantAccessReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_grantAccessReservation_admin.cedar"),
        },
        {
            "name": "create_reservation_member_floor",
            "description": "A user who is a member for reservations at a property MUST be able to createReservation on that property",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_createReservation_member.cedar"),
        },
        {
            "name": "view_property_viewer_floor",
            "description": "A user who is a viewer for reservations at a property MUST be able to viewProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_viewProperty_viewer.cedar"),
        },
        {
            "name": "create_hotel_admin_floor",
            "description": "A user who is a hotel admin at a hotel MUST be able to createHotel (sub-chain) on that hotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_createHotel_admin.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_updateReservation",
            "description": "updateReservation policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_createReservation",
            "description": "createReservation policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewProperty",
            "description": "viewProperty policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_updateProperty",
            "description": "updateProperty policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grantAccessProperty",
            "description": "grantAccessProperty policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_createProperty",
            "description": "createProperty policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_createHotel",
            "description": "createHotel policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_viewHotel",
            "description": "viewHotel policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_updateHotel",
            "description": "updateHotel policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_grantAccessHotel",
            "description": "grantAccessHotel policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
        },
    ]
