"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View access is bounded by: active project, one of three roles with their respective constraints, Phase-3 only for PI/DM, department match or GlobalAuditor, and compliant device for HighlyRestricted",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit access is bounded by: active project, one of three roles with their respective constraints, Phase-3 only for PI/DM, department match or GlobalAuditor, compliant device for HighlyRestricted, and patient consent required",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "active_project_gate_view",
            "description": "View is only allowed when projectStatus is Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_project_view.cedar"),
        },
        {
            "name": "active_project_gate_edit",
            "description": "Edit is only allowed when projectStatus is Active",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_project_edit.cedar"),
        },
        {
            "name": "consent_block_edit",
            "description": "Edit is never allowed when hasPatientConsent is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_consent_edit.cedar"),
        },
        {
            "name": "device_compliance_highly_restricted_view",
            "description": "View of HighlyRestricted documents requires compliant device",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_device_view.cedar"),
        },
        {
            "name": "device_compliance_highly_restricted_edit",
            "description": "Edit of HighlyRestricted documents requires compliant device",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_device_edit.cedar"),
        },
        {
            "name": "cross_dept_block_view",
            "description": "View requires department match or GlobalAuditor membership",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_view.cedar"),
        },
        {
            "name": "cross_dept_block_edit",
            "description": "Edit requires department match or GlobalAuditor membership",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_edit.cedar"),
        },
        {
            "name": "phase3_restriction_view",
            "description": "Phase-3 documents can only be viewed by PrincipalInvestigator or DataManager, not ClinicalResearcher",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_phase3_view.cedar"),
        },
        {
            "name": "phase3_restriction_edit",
            "description": "Phase-3 documents can only be edited by PrincipalInvestigator or DataManager, not ClinicalResearcher",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_phase3_edit.cedar"),
        },
        {
            "name": "role_gate_view",
            "description": "Only ClinicalResearcher, PrincipalInvestigator, or DataManager roles may View",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_role_gate_view.cedar"),
        },
        {
            "name": "role_gate_edit",
            "description": "Only ClinicalResearcher, PrincipalInvestigator, or DataManager roles may Edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_role_gate_edit.cedar"),
        },
        {
            "name": "floor_pi_view",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, active project, non-Phase3, non-HighlyRestricted doc MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "floor_cr_view",
            "description": "A ClinicalResearcher with clearance > 3, matching department, active project, non-Phase3, non-HighlyRestricted doc MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_view.cedar"),
        },
        {
            "name": "floor_dm_edit",
            "description": "A DataManager with clearance > 5, matching department, active project, non-Phase3, compliant device, patient consent MUST be able to Edit even HighlyRestricted",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_dm_edit.cedar"),
        },
        {
            "name": "floor_global_auditor_pi_view",
            "description": "A PrincipalInvestigator who is also GlobalAuditor with compliant device and low risk can View cross-department docs",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_auditor_crossdept_view.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
    ]
