"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "external_prez_view_safety",
            "description": "ExternalPrezViewActions (viewPresentation, removeSelfAccessFromPresentation) only permitted if principal in resource.viewers OR principal is owner/editor (via PrezEditActions/InternalPrezViewActions overlap)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_safety",
            "description": "duplicatePresentation only permitted if (principal.job == Job::internal AND principal in resource.viewers) OR principal == resource.owner OR principal in resource.editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_safety",
            "description": "editPresentation only permitted if principal == resource.owner OR principal in resource.editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "grant_view_presentation_safety",
            "description": "grantViewAccessToPresentation only permitted if principal == resource.owner OR principal in resource.editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewPresentation.cedar"),
        },
        {
            "name": "grant_edit_presentation_safety",
            "description": "grantEditAccessToPresentation only permitted if (principal == resource.owner OR principal in resource.editors) AND context.target.job == Job::internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditPresentation.cedar"),
        },
        {
            "name": "view_template_safety",
            "description": "viewTemplate only permitted if principal in resource.viewerMarkets OR (principal.job == Job::internal AND principal in resource.viewers) OR principal == resource.owner OR principal in resource.editors OR principal in resource.editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "duplicate_template_safety",
            "description": "duplicateTemplate only permitted if principal in resource.viewerMarkets OR (principal.job == Job::internal AND principal in resource.viewers) OR principal == resource.owner OR principal in resource.editors OR principal in resource.editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "edit_template_safety",
            "description": "editTemplate only permitted if principal == resource.owner OR principal in resource.editors OR principal in resource.editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_safety",
            "description": "grantEditAccessToTemplate only permitted if (principal == resource.owner OR principal in resource.editors OR principal in resource.editorMarkets) AND NOT (context has targetUser && context.targetUser.job != Job::internal)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditTemplate.cedar"),
        },
        {
            "name": "grant_view_template_safety",
            "description": "grantViewAccessToTemplate only permitted if principal == resource.owner OR principal in resource.editors OR principal in resource.editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewTemplate.cedar"),
        },
        {
            "name": "remove_self_template_safety",
            "description": "removeSelfAccessFromTemplate only permitted if (principal.job == Job::internal AND principal in resource.viewers) OR principal == resource.owner OR principal in resource.editors OR principal in resource.editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfTemplate.cedar"),
        },
        {
            "name": "remove_others_template_safety",
            "description": "removeOthersAccessToTemplate only permitted if principal == resource.owner OR principal in resource.editors OR principal in resource.editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersTemplate.cedar"),
        },
        {
            "name": "floor_external_viewer_view",
            "description": "A user in resource.viewers MUST be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_viewer_view.cedar"),
        },
        {
            "name": "floor_owner_edit_presentation",
            "description": "The owner of a presentation MUST be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_owner_editPresentation.cedar"),
        },
        {
            "name": "floor_editor_edit_presentation",
            "description": "An editor of a presentation MUST be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editor_editPresentation.cedar"),
        },
        {
            "name": "floor_market_viewer_viewTemplate",
            "description": "A user in resource.viewerMarkets MUST be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_market_viewer_viewTemplate.cedar"),
        },
        {
            "name": "floor_owner_editTemplate",
            "description": "The owner of a template MUST be able to editTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_owner_editTemplate.cedar"),
        },
        {
            "name": "floor_editorMarket_editTemplate",
            "description": "A user in resource.editorMarkets MUST be able to editTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_editorMarket_editTemplate.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantEditPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditTemplate",
            "description": "grantEditAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
        },
    ]
