"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_reservation_safety",
            "description": "viewReservation only if resource is in viewer/member propertyReservations or propertyAdminPermissions \u2014 hotel-level sets must NOT grant access",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "update_reservation_safety",
            "description": "updateReservation only if resource is in member propertyReservations or propertyAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grant_access_reservation_safety",
            "description": "grantAccessReservation only if resource is in propertyAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "create_reservation_safety",
            "description": "createReservation on a Property only if property is in member propertyReservations or propertyAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "view_property_safety",
            "description": "viewProperty only if property is in viewer/member propertyReservations or propertyAdminPermissions \u2014 hotel sets must NOT grant access",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "update_property_safety",
            "description": "updateProperty only if property is in member propertyReservations or propertyAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grant_access_property_safety",
            "description": "grantAccessProperty only if property is in propertyAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "view_hotel_safety",
            "description": "viewHotel only if hotel is in viewer/member hotelReservations or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "update_hotel_safety",
            "description": "updateHotel only if hotel is in member hotelReservations or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "grant_access_hotel_safety",
            "description": "grantAccessHotel only if hotel is in hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "create_property_safety",
            "description": "createProperty only if hotel is in member hotelReservations or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "create_hotel_safety",
            "description": "createHotel only if hotel is in member hotelReservations or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "viewer_view_reservation_floor",
            "description": "A viewer with property-level permission MUST be able to view reservations in that property",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewer_viewReservation.cedar"),
        },
        {
            "name": "member_update_reservation_floor",
            "description": "A member with property-level permission MUST be able to update reservations",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_member_updateReservation.cedar"),
        },
        {
            "name": "admin_grant_reservation_floor",
            "description": "A property admin MUST be able to grantAccessReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessReservation.cedar"),
        },
        {
            "name": "member_create_reservation_floor",
            "description": "A member with property-level permission MUST be able to createReservation on that property",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_member_createReservation.cedar"),
        },
        {
            "name": "viewer_view_property_floor",
            "description": "A viewer with property-level permission MUST be able to viewProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_viewer_viewProperty.cedar"),
        },
        {
            "name": "admin_grant_property_floor",
            "description": "A property admin MUST be able to grantAccessProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessProperty.cedar"),
        },
        {
            "name": "viewer_view_hotel_floor",
            "description": "A viewer with hotel-level permission MUST be able to viewHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_viewer_viewHotel.cedar"),
        },
        {
            "name": "admin_grant_hotel_floor",
            "description": "A hotel admin MUST be able to grantAccessHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessHotel.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_updateReservation",
            "description": "updateReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_createReservation",
            "description": "createReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewProperty",
            "description": "viewProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewHotel",
            "description": "viewHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_grantAccessHotel",
            "description": "grantAccessHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
        },
    ]
