"""Hand-generated verification plan for realworld/wide_set_50_elements.

Stress-tests Set<String> reasoning across 50 distinct capability strings.
1 ceiling + 25 floors (each pinning 2 specific cap strings) + 1 liveness.
"""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        # ── Safety ceiling ──────────────────────────────────────
        {"name": "useFeature_safety", "description": "useFeature permitted only when subscribedFeatures contains all requiredCapabilities", "type": "implies", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "reference_path": os.path.join(REFS, "useFeature_safety.cedar")},

        # ── Floors (25 specific capability-pair witnesses spanning cap_001..cap_050) ──
        {"name": "must_useFeature_caps_001_002", "description": "user with cap_001 and cap_002 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_001_002.cedar")},
        {"name": "must_useFeature_caps_003_004", "description": "user with cap_003 and cap_004 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_003_004.cedar")},
        {"name": "must_useFeature_caps_005_006", "description": "user with cap_005 and cap_006 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_005_006.cedar")},
        {"name": "must_useFeature_caps_007_008", "description": "user with cap_007 and cap_008 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_007_008.cedar")},
        {"name": "must_useFeature_caps_009_010", "description": "user with cap_009 and cap_010 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_009_010.cedar")},
        {"name": "must_useFeature_caps_011_012", "description": "user with cap_011 and cap_012 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_011_012.cedar")},
        {"name": "must_useFeature_caps_013_014", "description": "user with cap_013 and cap_014 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_013_014.cedar")},
        {"name": "must_useFeature_caps_015_016", "description": "user with cap_015 and cap_016 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_015_016.cedar")},
        {"name": "must_useFeature_caps_017_018", "description": "user with cap_017 and cap_018 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_017_018.cedar")},
        {"name": "must_useFeature_caps_019_020", "description": "user with cap_019 and cap_020 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_019_020.cedar")},
        {"name": "must_useFeature_caps_021_022", "description": "user with cap_021 and cap_022 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_021_022.cedar")},
        {"name": "must_useFeature_caps_023_024", "description": "user with cap_023 and cap_024 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_023_024.cedar")},
        {"name": "must_useFeature_caps_025_026", "description": "user with cap_025 and cap_026 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_025_026.cedar")},
        {"name": "must_useFeature_caps_027_028", "description": "user with cap_027 and cap_028 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_027_028.cedar")},
        {"name": "must_useFeature_caps_029_030", "description": "user with cap_029 and cap_030 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_029_030.cedar")},
        {"name": "must_useFeature_caps_031_032", "description": "user with cap_031 and cap_032 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_031_032.cedar")},
        {"name": "must_useFeature_caps_033_034", "description": "user with cap_033 and cap_034 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_033_034.cedar")},
        {"name": "must_useFeature_caps_035_036", "description": "user with cap_035 and cap_036 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_035_036.cedar")},
        {"name": "must_useFeature_caps_037_038", "description": "user with cap_037 and cap_038 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_037_038.cedar")},
        {"name": "must_useFeature_caps_039_040", "description": "user with cap_039 and cap_040 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_039_040.cedar")},
        {"name": "must_useFeature_caps_041_042", "description": "user with cap_041 and cap_042 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_041_042.cedar")},
        {"name": "must_useFeature_caps_043_044", "description": "user with cap_043 and cap_044 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_043_044.cedar")},
        {"name": "must_useFeature_caps_045_046", "description": "user with cap_045 and cap_046 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_045_046.cedar")},
        {"name": "must_useFeature_caps_047_048", "description": "user with cap_047 and cap_048 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_047_048.cedar")},
        {"name": "must_useFeature_caps_049_050", "description": "user with cap_049 and cap_050 MUST useFeature on Feature requiring subset of those caps", "type": "floor", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature", "floor_path": os.path.join(REFS, "must_useFeature_caps_049_050.cedar")},

        # ── Liveness ──────────────────────────────────────────────
        {"name": "liveness_useFeature", "description": "useFeature has at least one permitted request", "type": "always-denies-liveness", "principal_type": "User", "action": "Action::\"useFeature\"", "resource_type": "Feature"},
    ]
