"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "pull_safety",
            "description": "Pull access only for users who are readers of the repository",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_pull.cedar"),
        },
        {
            "name": "fork_safety",
            "description": "Fork access only for users who are readers of the repository",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_fork.cedar"),
        },
        {
            "name": "push_safety",
            "description": "Push access only for writers, and blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_push.cedar"),
        },
        {
            "name": "edit_issue_safety",
            "description": "Edit issue only if (reader AND reporter) OR writer of the repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_edit_issue.cedar"),
        },
        {
            "name": "delete_issue_safety",
            "description": "Delete issue only if (reader AND reporter) OR maintainer of the repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_delete_issue.cedar"),
        },
        {
            "name": "assign_issue_safety",
            "description": "Assign issue only for triagers of the repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_assign_issue.cedar"),
        },
        {
            "name": "add_reader_safety",
            "description": "add_reader only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_reader.cedar"),
        },
        {
            "name": "add_writer_safety",
            "description": "add_writer only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_writer.cedar"),
        },
        {
            "name": "add_maintainer_safety",
            "description": "add_maintainer only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_maintainer.cedar"),
        },
        {
            "name": "add_admin_safety",
            "description": "add_admin only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_admin.cedar"),
        },
        {
            "name": "add_triager_safety",
            "description": "add_triager only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_triager.cedar"),
        },
        {
            "name": "merge_pr_safety",
            "description": "merge_pr only for writers of PR's repo, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"merge_pr\"",
            "resource_type": "PullRequest",
            "reference_path": os.path.join(REFS, "ceiling_merge_pr.cedar"),
        },
        {
            "name": "approve_pr_safety",
            "description": "approve_pr only for readers of PR's repo, and author cannot self-approve",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"approve_pr\"",
            "resource_type": "PullRequest",
            "reference_path": os.path.join(REFS, "ceiling_approve_pr.cedar"),
        },
        {
            "name": "request_changes_safety",
            "description": "request_changes only for readers of PR's repo, and author cannot request changes on own PR",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"request_changes\"",
            "resource_type": "PullRequest",
            "reference_path": os.path.join(REFS, "ceiling_request_changes.cedar"),
        },
        {
            "name": "archived_blocks_push",
            "description": "Push must be denied on archived repos \u2014 ceiling is forbid when archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_push.cedar"),
        },
        {
            "name": "writer_edit_floor",
            "description": "Writers MUST be able to edit any issue in their repo (regardless of reporter)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_writer_edit.cedar"),
        },
        {
            "name": "reporter_delete_floor",
            "description": "Readers who are the reporter MUST be able to delete their own issue",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_reporter_delete.cedar"),
        },
        {
            "name": "reader_pull_floor",
            "description": "Readers MUST be able to pull from the repo (even if archived)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_pull.cedar"),
        },
        {
            "name": "reader_fork_floor",
            "description": "Readers MUST be able to fork the repo (even if archived)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_fork.cedar"),
        },
        {
            "name": "admin_add_reader_floor",
            "description": "Admins MUST be able to add_reader on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_reader.cedar"),
        },
        {
            "name": "writer_push_floor",
            "description": "Writers MUST be able to push to non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_writer_push.cedar"),
        },
        {
            "name": "writer_merge_pr_floor",
            "description": "Writers MUST be able to merge PRs on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"merge_pr\"",
            "resource_type": "PullRequest",
            "floor_path": os.path.join(REFS, "floor_writer_merge_pr.cedar"),
        },
        {
            "name": "reader_approve_pr_floor",
            "description": "Readers who are NOT the author MUST be able to approve PRs",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"approve_pr\"",
            "resource_type": "PullRequest",
            "floor_path": os.path.join(REFS, "floor_reader_approve_pr.cedar"),
        },
        {
            "name": "liveness_push",
            "description": "Push policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_edit_issue",
            "description": "Edit issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_delete_issue",
            "description": "Delete issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_assign_issue",
            "description": "Assign issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_add_reader",
            "description": "add_reader policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_merge_pr",
            "description": "merge_pr policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"merge_pr\"",
            "resource_type": "PullRequest",
        },
        {
            "name": "liveness_approve_pr",
            "description": "approve_pr policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"approve_pr\"",
            "resource_type": "PullRequest",
        },
        {
            "name": "liveness_pull",
            "description": "Pull policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_fork",
            "description": "Fork policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
        },
    ]
