"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "owner_view_document_ceiling",
            "description": "ViewDocument for Users is only allowed if: owner, in viewACL, in modifyACL, in manageACL, or publicAccess is view/edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_user.cedar"),
        },
        {
            "name": "public_view_document_ceiling",
            "description": "ViewDocument for Public is only allowed if publicAccess is view or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_public.cedar"),
        },
        {
            "name": "modify_document_user_ceiling",
            "description": "ModifyDocument for Users is only allowed if: owner, in modifyACL, or publicAccess is edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_document_user.cedar"),
        },
        {
            "name": "delete_document_ceiling",
            "description": "DeleteDocument only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete_document.cedar"),
        },
        {
            "name": "edit_is_private_ceiling",
            "description": "EditIsPrivate only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "edit_public_access_ceiling",
            "description": "EditPublicAccess only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "add_to_share_acl_ceiling",
            "description": "AddToShareACL only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "delete_group_ceiling",
            "description": "DeleteGroup only allowed if principal is the group owner and authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "modify_group_ceiling",
            "description": "ModifyGroup only allowed if principal is the group owner and authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "view_metadata_user_ceiling",
            "description": "ViewMetadata for Users is allowed if: owner, in viewACL, modifyACL, manageACL, or publicAccess is preview/view/edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewMetadata\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_metadata_user.cedar"),
        },
        {
            "name": "view_metadata_public_ceiling",
            "description": "ViewMetadata for Public is allowed if publicAccess is preview, view, or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewMetadata\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_metadata_public.cedar"),
        },
        {
            "name": "owner_view_document_floor",
            "description": "Owner who is authenticated and not blocked MUST be able to ViewDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view_document.cedar"),
        },
        {
            "name": "owner_modify_document_floor",
            "description": "Owner who is authenticated and not blocked MUST be able to ModifyDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify_document.cedar"),
        },
        {
            "name": "owner_delete_document_floor",
            "description": "Owner who is authenticated MUST be able to DeleteDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete_document.cedar"),
        },
        {
            "name": "view_acl_floor",
            "description": "User in viewACL who is authenticated and not blocked MUST be able to ViewDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl_view.cedar"),
        },
        {
            "name": "modify_acl_floor",
            "description": "User in modifyACL who is authenticated and not blocked MUST be able to ModifyDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl_modify.cedar"),
        },
        {
            "name": "manage_acl_add_share_floor",
            "description": "User in manageACL who is authenticated MUST be able to AddToShareACL",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_add_share.cedar"),
        },
        {
            "name": "public_view_document_floor",
            "description": "Public principal MUST be able to ViewDocument when publicAccess is view",
            "type": "floor",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_public_view_document.cedar"),
        },
        {
            "name": "public_preview_view_metadata_floor",
            "description": "Public principal MUST be able to ViewMetadata when publicAccess is preview",
            "type": "floor",
            "principal_type": "Public",
            "action": "Action::\"ViewMetadata\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_public_preview_metadata.cedar"),
        },
        {
            "name": "group_owner_delete_floor",
            "description": "Group owner who is authenticated MUST be able to DeleteGroup",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_delete.cedar"),
        },
        {
            "name": "user_public_edit_modify_floor",
            "description": "Authenticated user MUST be able to ModifyDocument when publicAccess is edit and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_user_public_edit_modify.cedar"),
        },
        {
            "name": "liveness_view_document_user",
            "description": "ViewDocument for Users is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document_user",
            "description": "ModifyDocument for Users is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_create_document",
            "description": "CreateDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_create_group",
            "description": "CreateGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_view_metadata_public",
            "description": "ViewMetadata for Public is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Public",
            "action": "Action::\"ViewMetadata\"",
            "resource_type": "Document",
        },
    ]
