"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View is only allowed when project is active, user is in ClinicalResearcher or PrincipalInvestigator role, and respective role constraints are met",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit is only allowed when project is active, user is in ClinicalResearcher or PrincipalInvestigator role, and respective role constraints are met",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "export_safety_ceiling",
            "description": "Export is only allowed when project is active, user is in correct role, role constraints are met, and device is compliant for all roles",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Export\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_export.cedar"),
        },
        {
            "name": "cross_dept_block_view",
            "description": "View is forbidden when user department does not match project managing department, unless user is GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_dept.cedar"),
        },
        {
            "name": "cross_dept_block_edit",
            "description": "Edit is forbidden when user department does not match project managing department, unless user is GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_dept.cedar"),
        },
        {
            "name": "cross_dept_block_export",
            "description": "Export is forbidden when user department does not match project managing department, unless user is GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Export\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_export_dept.cedar"),
        },
        {
            "name": "floor_clinical_researcher_view",
            "description": "A ClinicalResearcher with clearanceLevel > 3, matching department, active project, non-HighlyRestricted doc MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_view.cedar"),
        },
        {
            "name": "floor_pi_view",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, active project MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "floor_clinical_researcher_edit",
            "description": "A ClinicalResearcher with clearanceLevel > 3, matching department, active project, non-HighlyRestricted doc MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_edit.cedar"),
        },
        {
            "name": "floor_pi_edit",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, active project MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_edit.cedar"),
        },
        {
            "name": "floor_cr_export",
            "description": "A ClinicalResearcher with clearanceLevel > 3, matching department, active project, non-HighlyRestricted doc, compliant device MUST be able to Export",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Export\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_cr_export.cedar"),
        },
        {
            "name": "floor_pi_export",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, active project MUST be able to Export",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Export\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_export.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_export",
            "description": "Export policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Export\"",
            "resource_type": "Document",
        },
    ]
