"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "update_workspace_role_safety",
            "description": "UpdateWorkspace is only permitted if principal is in Role-A",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_update.cedar"),
        },
        {
            "name": "delete_workspace_role_safety",
            "description": "DeleteWorkspace is only permitted if principal is in Role-A",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_delete.cedar"),
        },
        {
            "name": "read_workspace_role_safety",
            "description": "ReadWorkspace is only permitted if principal is in Role-A or Role-B",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_read.cedar"),
        },
        {
            "name": "archive_workspace_role_safety",
            "description": "ArchiveWorkspace is only permitted if principal is in Role-C",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ArchiveWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_archive.cedar"),
        },
        {
            "name": "update_workspace_tag_safety",
            "description": "UpdateWorkspace requires tag matching: for each dimension present on both user (Role-A) and workspace, user set contains ALL or workspace set contains ALL or user containsAll workspace",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_update_tags.cedar"),
        },
        {
            "name": "delete_workspace_tag_safety",
            "description": "DeleteWorkspace requires tag matching under Role-A",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_delete_tags.cedar"),
        },
        {
            "name": "archive_workspace_tag_safety",
            "description": "ArchiveWorkspace requires tag matching under Role-C",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ArchiveWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_archive_tags.cedar"),
        },
        {
            "name": "floor_update_all_wildcard",
            "description": "A user in Role-A whose allowedTagsForRole Role-A has ALL in every present dimension MUST be able to UpdateWorkspace regardless of workspace tags",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_update_all.cedar"),
        },
        {
            "name": "floor_delete_all_wildcard",
            "description": "A user in Role-A whose allowedTagsForRole Role-A has ALL in every present dimension MUST be able to DeleteWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_delete_all.cedar"),
        },
        {
            "name": "floor_read_roleA_all_wildcard",
            "description": "A user in Role-A whose allowedTagsForRole Role-A has ALL in every present dimension MUST be able to ReadWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_read_roleA_all.cedar"),
        },
        {
            "name": "floor_read_roleB_all_wildcard",
            "description": "A user in Role-B whose allowedTagsForRole Role-B has ALL in every present dimension MUST be able to ReadWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_read_roleB_all.cedar"),
        },
        {
            "name": "floor_archive_all_wildcard",
            "description": "A user in Role-C whose allowedTagsForRole Role-C has ALL in every present dimension MUST be able to ArchiveWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ArchiveWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_archive_all.cedar"),
        },
        {
            "name": "floor_archive_no_tags",
            "description": "A user in Role-C with Role-C entry but no tag dimensions, and workspace with no tag dimensions, MUST be able to ArchiveWorkspace (missing tags pass)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ArchiveWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_archive_no_tags.cedar"),
        },
        {
            "name": "liveness_update",
            "description": "UpdateWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_delete",
            "description": "DeleteWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_read",
            "description": "ReadWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_archive",
            "description": "ArchiveWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ArchiveWorkspace\"",
            "resource_type": "Workspace",
        },
    ]
