"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_reservation_viewer_ceiling",
            "description": "viewReservation only permitted if resource is in viewer, member, or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "update_reservation_ceiling",
            "description": "updateReservation only permitted if resource is in member or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grant_access_reservation_ceiling",
            "description": "grantAccessReservation only permitted if resource is in admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "create_reservation_ceiling",
            "description": "createReservation only permitted if resource (Property) is in member or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "view_property_ceiling",
            "description": "viewProperty only permitted if resource is in viewer, member, or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "update_property_ceiling",
            "description": "updateProperty only permitted if resource is in member or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grant_access_property_ceiling",
            "description": "grantAccessProperty only permitted if resource is in admin permission sets (hotel or property)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "view_hotel_ceiling",
            "description": "viewHotel only permitted if resource is in viewer, member, or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "update_hotel_ceiling",
            "description": "updateHotel only permitted if resource is in member or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "create_hotel_ceiling",
            "description": "createHotel only permitted if resource is in member or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "create_property_ceiling",
            "description": "createProperty only permitted if resource (Hotel) is in member or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "grant_access_hotel_ceiling",
            "description": "grantAccessHotel only permitted if resource is in admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "guest_view_reservation_ceiling",
            "description": "guestViewReservation only permitted if resource is in the guest's reservations set",
            "type": "implies",
            "principal_type": "Guest",
            "action": "Action::\"guestViewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_guestViewReservation.cedar"),
        },
        {
            "name": "floor_viewer_view_reservation_hotel",
            "description": "A user with the reservation's parent in viewPermissions.hotelReservations MUST be able to viewReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewer_viewReservation_hotel.cedar"),
        },
        {
            "name": "floor_admin_grant_access_reservation_hotel",
            "description": "A user with the reservation's parent hotel in hotelAdminPermissions MUST be able to grantAccessReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessReservation_hotel.cedar"),
        },
        {
            "name": "floor_guest_view_reservation",
            "description": "A guest whose reservations set contains the resource MUST be able to guestViewReservation",
            "type": "floor",
            "principal_type": "Guest",
            "action": "Action::\"guestViewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_guestViewReservation.cedar"),
        },
        {
            "name": "floor_member_update_property_hotel",
            "description": "A user with the property's hotel in memberPermissions.hotelReservations MUST be able to updateProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_member_updateProperty_hotel.cedar"),
        },
        {
            "name": "floor_admin_grant_access_hotel",
            "description": "A user with the hotel in hotelAdminPermissions MUST be able to grantAccessHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessHotel.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_updateReservation",
            "description": "updateReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_guestViewReservation",
            "description": "guestViewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Guest",
            "action": "Action::\"guestViewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_viewProperty",
            "description": "viewProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grantAccessProperty",
            "description": "grantAccessProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewHotel",
            "description": "viewHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_grantAccessHotel",
            "description": "grantAccessHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
        },
    ]
