"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_reservation_safety",
            "description": "viewReservation only if user has viewer, member, or admin permissions covering the reservation's property/hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "update_reservation_safety",
            "description": "updateReservation only if user has member or admin permissions covering the reservation's property/hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grant_access_reservation_safety",
            "description": "grantAccessReservation only if user has admin permissions covering the reservation's property/hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "view_property_safety",
            "description": "viewProperty only if user has viewer, member, or admin permissions covering the property",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "update_property_safety",
            "description": "updateProperty only if user has member or admin permissions covering the property",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grant_access_property_safety",
            "description": "grantAccessProperty only if user has admin permissions covering the property",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "create_reservation_safety",
            "description": "createReservation only if user has member or admin permissions covering the property",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "view_hotel_safety",
            "description": "viewHotel only if user has viewer, member, or admin permissions covering the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "update_hotel_safety",
            "description": "updateHotel only if user has member or admin permissions covering the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "create_property_safety",
            "description": "createProperty only if user has member or admin permissions covering the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "create_hotel_safety",
            "description": "createHotel only if user has member or admin permissions covering the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "grant_access_hotel_safety",
            "description": "grantAccessHotel only if user has admin permissions covering the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "view_rates_safety",
            "description": "viewRates only if user has at least viewer permissions AND (in-season OR admin)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewRates\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewRates.cedar"),
        },
        {
            "name": "floor_viewer_viewReservation",
            "description": "A user with viewer hotel permissions MUST be able to viewReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewer_viewReservation.cedar"),
        },
        {
            "name": "floor_member_updateReservation",
            "description": "A user with member hotel permissions MUST be able to updateReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_member_updateReservation.cedar"),
        },
        {
            "name": "floor_admin_grantAccessReservation",
            "description": "A user with hotel admin permissions MUST be able to grantAccessReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessReservation.cedar"),
        },
        {
            "name": "floor_admin_viewRates_outOfSeason",
            "description": "Admin users MUST be able to viewRates even outside the season window",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewRates\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_admin_viewRates.cedar"),
        },
        {
            "name": "floor_viewer_viewRates_inSeason",
            "description": "Viewer users MUST be able to viewRates when currentTime is within season window",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewRates\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_viewer_viewRates_inSeason.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_updateReservation",
            "description": "updateReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_viewRates",
            "description": "viewRates is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewRates\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewProperty",
            "description": "viewProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_createReservation",
            "description": "createReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewHotel",
            "description": "viewHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_grantAccessHotel",
            "description": "grantAccessHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
        },
    ]
