"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "external_prez_view_safety",
            "description": "ExternalPrezViewActions (viewPresentation) only permitted if principal in resource.viewers OR principal is owner/editor (via PrezEditActions path)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_safety",
            "description": "duplicatePresentation only if (internal AND in viewers) OR owner OR in editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_safety",
            "description": "editPresentation only if (owner OR in editors) AND not archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "grant_view_prez_safety",
            "description": "grantViewAccessToPresentation only if (owner OR in editors) AND not archived AND customer sharing restriction satisfied",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "grant_edit_prez_safety",
            "description": "grantEditAccessToPresentation only if (owner OR in editors) AND not archived AND target is internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "delete_presentation_safety",
            "description": "deletePresentation only if owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"deletePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_deletePresentation.cedar"),
        },
        {
            "name": "view_template_safety",
            "description": "viewTemplate only if (internal AND in viewers) OR (in viewerMarkets) OR owner OR in editors OR in editorMarkets OR regional manager with overlapping managed markets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "edit_template_safety",
            "description": "editTemplate only if (owner OR in editors OR in editorMarkets OR regional manager overlap) AND approval gate respected",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "grant_view_template_safety",
            "description": "grantViewAccessToTemplate only if editor-level access AND template grant restriction respected AND approval gate respected",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_safety",
            "description": "grantEditAccessToTemplate only if editor-level access AND target is internal AND approval gate respected",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "remove_self_prez_floor",
            "description": "Users in resource.viewers MUST be able to removeSelfAccessFromPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "owner_delete_floor",
            "description": "Owner MUST be able to delete presentation even if archived",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"deletePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_deletePresentation.cedar"),
        },
        {
            "name": "owner_edit_prez_floor",
            "description": "Owner MUST be able to editPresentation when not archived",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editPresentation.cedar"),
        },
        {
            "name": "market_viewer_template_floor",
            "description": "Users in viewerMarkets MUST be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_viewTemplate_market.cedar"),
        },
        {
            "name": "template_owner_edit_floor",
            "description": "Internal template owner MUST be able to editTemplate (bypasses approval gate)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_editTemplate_owner.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_deletePresentation",
            "description": "deletePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"deletePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
    ]
