"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "external_prez_view_safety",
            "description": "ExternalPrezViewActions (viewPresentation) only permitted if principal in resource.viewers OR resource.owner == principal OR principal in resource.editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_safety",
            "description": "duplicatePresentation only permitted if (principal.job == Job::\"internal\" AND principal in resource.viewers) OR resource.owner == principal OR principal in resource.editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_safety",
            "description": "editPresentation only permitted if resource.owner == principal OR principal in resource.editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "grant_view_prez_safety",
            "description": "grantViewAccessToPresentation only if editor/owner AND customer sharing restriction respected",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "grant_edit_prez_safety",
            "description": "grantEditAccessToPresentation only if editor/owner AND target is internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "delete_presentation_safety",
            "description": "deletePresentation only permitted if resource.owner == principal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"deletePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_deletePresentation.cedar"),
        },
        {
            "name": "view_template_safety",
            "description": "viewTemplate only if (internal AND in viewers) OR (in viewerMarkets) OR owner OR in editors OR in editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "edit_template_safety",
            "description": "editTemplate only if owner OR in editors OR in editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "grant_view_template_safety",
            "description": "grantViewAccessToTemplate only if editor/owner/editorMarket AND customer restriction respected",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_safety",
            "description": "grantEditAccessToTemplate only if editor/owner/editorMarket AND targetUser (if present) is internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "floor_owner_edit_presentation",
            "description": "Owner MUST be able to edit their own presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editPresentation.cedar"),
        },
        {
            "name": "floor_viewer_view_presentation",
            "description": "A viewer MUST be able to view a presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_viewPresentation.cedar"),
        },
        {
            "name": "floor_delete_presentation_owner",
            "description": "Owner MUST be able to delete their own presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"deletePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_deletePresentation.cedar"),
        },
        {
            "name": "floor_market_view_template",
            "description": "User in viewerMarkets MUST be able to view template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_viewTemplate_market.cedar"),
        },
        {
            "name": "floor_owner_edit_template",
            "description": "Owner MUST be able to edit their own template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_editTemplate.cedar"),
        },
        {
            "name": "liveness_view_presentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_delete_presentation",
            "description": "deletePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"deletePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_edit_template",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grant_view_prez",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
    ]
