"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "owner_view_safety",
            "description": "ViewDocument by User is only allowed if: owner, in viewACL, in modifyACL (through manage/modify paths), publicAccess is view/edit, or manageACL membership \u2014 but always bounded by owner OR viewACL OR modifyACL OR manageACL OR publicAccess",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_user.cedar"),
        },
        {
            "name": "public_view_safety",
            "description": "ViewDocument by Public is only allowed if publicAccess is view or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_public.cedar"),
        },
        {
            "name": "modify_safety",
            "description": "ModifyDocument is only allowed if owner, in modifyACL, or publicAccess == edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify.cedar"),
        },
        {
            "name": "delete_safety",
            "description": "DeleteDocument is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete.cedar"),
        },
        {
            "name": "edit_private_safety",
            "description": "EditIsPrivate is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_private.cedar"),
        },
        {
            "name": "edit_public_access_safety",
            "description": "EditPublicAccess is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "add_share_acl_safety",
            "description": "AddToShareACL is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_share_acl.cedar"),
        },
        {
            "name": "delete_group_safety",
            "description": "DeleteGroup is only allowed if principal is the group owner and is authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "modify_group_safety",
            "description": "ModifyGroup is only allowed if principal is the group owner and is authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "auth_required_view",
            "description": "Unauthenticated users must be denied ViewDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_view.cedar"),
        },
        {
            "name": "auth_required_modify",
            "description": "Unauthenticated users must be denied ModifyDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_modify.cedar"),
        },
        {
            "name": "auth_required_delete",
            "description": "Unauthenticated users must be denied DeleteDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_delete.cedar"),
        },
        {
            "name": "block_view_safety",
            "description": "ViewDocument must be denied if principal is in owner's blocked set or owner is in principal's blocked set (for Users)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_block_view.cedar"),
        },
        {
            "name": "block_modify_safety",
            "description": "ModifyDocument must be denied if principal is in owner's blocked set or owner is in principal's blocked set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_block_modify.cedar"),
        },
        {
            "name": "owner_view_floor",
            "description": "Owner who is authenticated, not blocked, and document not expired MUST be able to ViewDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view.cedar"),
        },
        {
            "name": "owner_delete_floor",
            "description": "Owner who is authenticated MUST be able to DeleteDocument even on expired documents",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete.cedar"),
        },
        {
            "name": "view_acl_floor",
            "description": "User in viewACL who is authenticated, not blocked, and doc not expired MUST be able to ViewDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl.cedar"),
        },
        {
            "name": "modify_acl_floor",
            "description": "User in modifyACL who is authenticated, not blocked, and doc not expired MUST be able to ModifyDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl.cedar"),
        },
        {
            "name": "group_owner_delete_floor",
            "description": "Group owner who is authenticated MUST be able to DeleteGroup",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_delete.cedar"),
        },
        {
            "name": "group_owner_modify_floor",
            "description": "Group owner who is authenticated MUST be able to ModifyGroup",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_modify.cedar"),
        },
        {
            "name": "liveness_view_user",
            "description": "ViewDocument for User is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_view_public",
            "description": "ViewDocument for Public is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify",
            "description": "ModifyDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete",
            "description": "DeleteDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_share",
            "description": "AddToShareACL is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_create_document",
            "description": "CreateDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_create_group",
            "description": "CreateGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
        },
        {
            "name": "expiry_deny_view_safety",
            "description": "Expired documents: non-owner Users cannot ViewDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_expiry_view.cedar"),
        },
        {
            "name": "expiry_deny_modify_safety",
            "description": "Expired documents: non-owner Users cannot ModifyDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_expiry_modify.cedar"),
        },
        {
            "name": "expiry_deny_add_share_safety",
            "description": "Expired documents: non-owner Users cannot AddToShareACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_expiry_add_share.cedar"),
        },
    ]
