"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_reservation_ceiling",
            "description": "viewReservation only allowed via viewer, member, or admin permission sets at franchise, hotel, or property level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "update_reservation_ceiling",
            "description": "updateReservation only allowed via member or admin permission sets at franchise, hotel, or property level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grant_access_reservation_ceiling",
            "description": "grantAccessReservation only allowed via admin permission sets at franchise, hotel, or property level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "view_property_ceiling",
            "description": "viewProperty only allowed via viewer, member, or admin permission sets at franchise, hotel, or property level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "create_reservation_ceiling",
            "description": "createReservation only allowed via member or admin permission sets at franchise, hotel, or property level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "update_property_ceiling",
            "description": "updateProperty only allowed via member or admin permission sets at franchise, hotel, or property level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grant_access_property_ceiling",
            "description": "grantAccessProperty only allowed via admin permission sets at franchise, hotel, or property level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "view_hotel_ceiling",
            "description": "viewHotel only allowed via viewer, member, or admin permission sets at franchise or hotel level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "create_property_ceiling",
            "description": "createProperty only allowed via member or admin permission sets at franchise or hotel level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "create_hotel_ceiling",
            "description": "createHotel only allowed via member or admin permission sets at franchise or hotel level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "update_hotel_ceiling",
            "description": "updateHotel only allowed via member or admin permission sets at franchise or hotel level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "grant_access_hotel_ceiling",
            "description": "grantAccessHotel only allowed via admin permission sets at franchise or hotel level",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "view_franchise_ceiling",
            "description": "viewFranchise only allowed via viewer, member, or admin franchise-level permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewFranchise\"",
            "resource_type": "Franchise",
            "reference_path": os.path.join(REFS, "ceiling_viewFranchise.cedar"),
        },
        {
            "name": "update_franchise_ceiling",
            "description": "updateFranchise only allowed via member or admin franchise-level permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateFranchise\"",
            "resource_type": "Franchise",
            "reference_path": os.path.join(REFS, "ceiling_updateFranchise.cedar"),
        },
        {
            "name": "grant_access_franchise_ceiling",
            "description": "grantAccessFranchise only allowed via franchiseAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessFranchise\"",
            "resource_type": "Franchise",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessFranchise.cedar"),
        },
        {
            "name": "viewer_franchise_reservation_floor",
            "description": "Users with franchise-level viewer permissions MUST be able to viewReservation for reservations in that franchise",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewer_franchise_viewReservation.cedar"),
        },
        {
            "name": "member_franchise_update_reservation_floor",
            "description": "Users with franchise-level member permissions MUST be able to updateReservation for reservations in that franchise",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_member_franchise_updateReservation.cedar"),
        },
        {
            "name": "admin_franchise_grant_reservation_floor",
            "description": "Users with franchise-level admin permissions MUST be able to grantAccessReservation for reservations in that franchise",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_admin_franchise_grantAccessReservation.cedar"),
        },
        {
            "name": "admin_franchise_grant_franchise_floor",
            "description": "Users with franchiseAdminPermissions MUST be able to grantAccessFranchise",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessFranchise\"",
            "resource_type": "Franchise",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessFranchise.cedar"),
        },
        {
            "name": "member_franchise_update_franchise_floor",
            "description": "Users with franchise-level member permissions MUST be able to updateFranchise",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateFranchise\"",
            "resource_type": "Franchise",
            "floor_path": os.path.join(REFS, "floor_member_updateFranchise.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_updateReservation",
            "description": "updateReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_viewProperty",
            "description": "viewProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grantAccessFranchise",
            "description": "grantAccessFranchise is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessFranchise\"",
            "resource_type": "Franchise",
        },
        {
            "name": "liveness_updateFranchise",
            "description": "updateFranchise is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateFranchise\"",
            "resource_type": "Franchise",
        },
    ]
