"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "owner_view_safety",
            "description": "ViewDocument by User is only allowed if owner, in viewACL, in modifyACL (for public edit path), in manageACL, or publicAccess allows it",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_user.cedar"),
        },
        {
            "name": "public_view_safety",
            "description": "ViewDocument by Public is only allowed if publicAccess is view or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_public.cedar"),
        },
        {
            "name": "modify_safety",
            "description": "ModifyDocument is only allowed if owner, in modifyACL, or publicAccess is edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify.cedar"),
        },
        {
            "name": "delete_safety",
            "description": "DeleteDocument is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete.cedar"),
        },
        {
            "name": "edit_isprivate_safety",
            "description": "EditIsPrivate is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_isprivate.cedar"),
        },
        {
            "name": "edit_publicaccess_safety",
            "description": "EditPublicAccess is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_publicaccess.cedar"),
        },
        {
            "name": "add_to_share_acl_safety",
            "description": "AddToShareACL is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "delete_group_safety",
            "description": "DeleteGroup is only allowed if principal is the group owner and authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "modify_group_safety",
            "description": "ModifyGroup is only allowed if principal is the group owner and authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "auth_deny_view",
            "description": "Unauthenticated Users cannot ViewDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_view.cedar"),
        },
        {
            "name": "auth_deny_modify",
            "description": "Unauthenticated Users cannot ModifyDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_modify.cedar"),
        },
        {
            "name": "auth_deny_delete",
            "description": "Unauthenticated Users cannot DeleteDocument",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_delete.cedar"),
        },
        {
            "name": "auth_deny_delete_group",
            "description": "Unauthenticated Users cannot DeleteGroup",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_auth_delete_group.cedar"),
        },
        {
            "name": "owner_view_floor",
            "description": "Owner MUST be able to ViewDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view.cedar"),
        },
        {
            "name": "owner_modify_floor",
            "description": "Owner MUST be able to ModifyDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify.cedar"),
        },
        {
            "name": "owner_delete_floor",
            "description": "Owner MUST be able to DeleteDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete.cedar"),
        },
        {
            "name": "owner_add_share_floor",
            "description": "Owner MUST be able to AddToShareACL when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_add_share.cedar"),
        },
        {
            "name": "view_acl_floor",
            "description": "User in viewACL MUST be able to ViewDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl.cedar"),
        },
        {
            "name": "modify_acl_floor",
            "description": "User in modifyACL MUST be able to ModifyDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl.cedar"),
        },
        {
            "name": "manage_acl_delete_floor",
            "description": "User in manageACL MUST be able to DeleteDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_delete.cedar"),
        },
        {
            "name": "public_view_floor",
            "description": "Public principal MUST be able to ViewDocument when publicAccess is view",
            "type": "floor",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_public_view.cedar"),
        },
        {
            "name": "group_owner_delete_floor",
            "description": "Group owner MUST be able to DeleteGroup when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_delete.cedar"),
        },
        {
            "name": "group_owner_modify_floor",
            "description": "Group owner MUST be able to ModifyGroup when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_modify.cedar"),
        },
        {
            "name": "liveness_view_document",
            "description": "ViewDocument policy is not trivially deny-all for Users",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document",
            "description": "ModifyDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_create_document",
            "description": "CreateDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_create_group",
            "description": "CreateGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_modify_group",
            "description": "ModifyGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
        },
    ]
