"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "auth_gate_forbid_create_document",
            "description": "CreateDocument is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
            "reference_path": os.path.join(REFS, "ceiling_create_document.cedar"),
        },
        {
            "name": "auth_gate_forbid_view_document_user",
            "description": "ViewDocument by User is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_user.cedar"),
        },
        {
            "name": "auth_gate_forbid_view_document_public",
            "description": "ViewDocument by Public is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_public.cedar"),
        },
        {
            "name": "auth_gate_forbid_modify_document",
            "description": "ModifyDocument is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_document.cedar"),
        },
        {
            "name": "auth_gate_forbid_delete_document",
            "description": "DeleteDocument is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete_document.cedar"),
        },
        {
            "name": "auth_gate_forbid_edit_is_private",
            "description": "EditIsPrivate is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "auth_gate_forbid_add_to_share_acl",
            "description": "AddToShareACL is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "auth_gate_forbid_edit_public_access",
            "description": "EditPublicAccess is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "auth_gate_forbid_create_group",
            "description": "CreateGroup is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
            "reference_path": os.path.join(REFS, "ceiling_create_group.cedar"),
        },
        {
            "name": "auth_gate_forbid_modify_group",
            "description": "ModifyGroup is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "auth_gate_forbid_delete_group",
            "description": "DeleteGroup is forbidden when is_authenticated is false",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "delete_document_owner_only",
            "description": "DeleteDocument is only allowed for the document owner (ceiling)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete_document.cedar"),
        },
        {
            "name": "edit_is_private_owner_only",
            "description": "EditIsPrivate is only allowed for the document owner (ceiling)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "modify_group_owner_only",
            "description": "ModifyGroup is only allowed for the group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "delete_group_owner_only",
            "description": "DeleteGroup is only allowed for the group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "view_document_user_ceiling",
            "description": "ViewDocument by User is allowed only if owner or in viewACL (and not private), with auth and no blocking",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_user.cedar"),
        },
        {
            "name": "view_document_public_ceiling",
            "description": "ViewDocument by Public only when publicAccess is view or edit and not private, with auth",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_public.cedar"),
        },
        {
            "name": "modify_document_ceiling",
            "description": "ModifyDocument allowed only if owner or in modifyACL (and not private), with auth and no blocking",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_document.cedar"),
        },
        {
            "name": "add_to_share_acl_ceiling",
            "description": "AddToShareACL allowed only if owner or in manageACL, with auth and no blocking",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "edit_public_access_ceiling",
            "description": "EditPublicAccess allowed only if owner or in manageACL, with auth and no blocking",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "private_doc_guard_view",
            "description": "Private documents cannot be viewed by non-owners (forbid guard rail)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_user.cedar"),
        },
        {
            "name": "private_doc_guard_modify",
            "description": "Private documents cannot be modified by non-owners",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_document.cedar"),
        },
        {
            "name": "floor_create_document",
            "description": "Any authenticated User MUST be able to CreateDocument on Drive",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
            "floor_path": os.path.join(REFS, "floor_create_document.cedar"),
        },
        {
            "name": "floor_create_group",
            "description": "Any authenticated User MUST be able to CreateGroup on Drive",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
            "floor_path": os.path.join(REFS, "floor_create_group.cedar"),
        },
        {
            "name": "floor_owner_view",
            "description": "An authenticated document owner MUST be able to ViewDocument (even if private), assuming no self-block",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view.cedar"),
        },
        {
            "name": "floor_owner_modify",
            "description": "An authenticated document owner MUST be able to ModifyDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify.cedar"),
        },
        {
            "name": "floor_owner_delete",
            "description": "An authenticated document owner MUST be able to DeleteDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete.cedar"),
        },
        {
            "name": "floor_owner_edit_is_private",
            "description": "An authenticated document owner MUST be able to EditIsPrivate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_edit_is_private.cedar"),
        },
        {
            "name": "floor_owner_add_to_share_acl",
            "description": "An authenticated document owner MUST be able to AddToShareACL",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_add_to_share_acl.cedar"),
        },
        {
            "name": "floor_owner_edit_public_access",
            "description": "An authenticated document owner MUST be able to EditPublicAccess",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_edit_public_access.cedar"),
        },
        {
            "name": "floor_group_owner_modify_group",
            "description": "An authenticated group owner MUST be able to ModifyGroup",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_modify_group.cedar"),
        },
        {
            "name": "floor_group_owner_delete_group",
            "description": "An authenticated group owner MUST be able to DeleteGroup",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_delete_group.cedar"),
        },
        {
            "name": "liveness_create_document",
            "description": "CreateDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_view_document_user",
            "description": "ViewDocument by User is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_view_document_public",
            "description": "ViewDocument by Public is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document",
            "description": "ModifyDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit_is_private",
            "description": "EditIsPrivate policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit_public_access",
            "description": "EditPublicAccess policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_create_group",
            "description": "CreateGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_modify_group",
            "description": "ModifyGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
    ]
