"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_presentation_safety",
            "description": "viewPresentation only if: (principal in resource.viewers) OR (resource.owner == principal) OR (principal in resource.editors). All paths blocked for non-internal outside campaign window.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "remove_self_presentation_safety",
            "description": "removeSelfAccessFromPresentation only if viewer or editor or owner, blocked for non-internal outside campaign window.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_safety",
            "description": "duplicatePresentation only if (internal + viewer) or owner or editor, blocked for non-internal outside campaign window.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_safety",
            "description": "editPresentation only if owner or editor, blocked for non-internal outside campaign window.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "grant_view_presentation_safety",
            "description": "grantViewAccessToPresentation only if owner or editor, subject to customer sharing restriction and campaign window.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewPresentation.cedar"),
        },
        {
            "name": "grant_edit_presentation_safety",
            "description": "grantEditAccessToPresentation only if owner or editor, target must be internal, subject to campaign window.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditPresentation.cedar"),
        },
        {
            "name": "view_template_safety",
            "description": "viewTemplate only if (in viewerMarkets) or (internal + in viewers) or (owner or editor or in editorMarkets).",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "duplicate_template_safety",
            "description": "duplicateTemplate only if (in viewerMarkets) or (internal + in viewers) or (owner or editor or in editorMarkets).",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "remove_self_template_safety",
            "description": "removeSelfAccessFromTemplate only if (internal + in viewers) or (owner or editor or in editorMarkets).",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfTemplate.cedar"),
        },
        {
            "name": "edit_template_safety",
            "description": "editTemplate only if owner or editor or in editorMarkets.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "remove_others_template_safety",
            "description": "removeOthersAccessToTemplate only if owner or editor or in editorMarkets.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersTemplate.cedar"),
        },
        {
            "name": "grant_view_template_safety",
            "description": "grantViewAccessToTemplate only if owner or editor or in editorMarkets, subject to customer sharing restriction on targetUser.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_safety",
            "description": "grantEditAccessToTemplate only if owner or editor or in editorMarkets, targetUser must be internal if present.",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditTemplate.cedar"),
        },
        {
            "name": "owner_edit_presentation_floor",
            "description": "Owner of a presentation MUST be able to editPresentation when internal (exempt from campaign window).",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_ownerEditPresentation.cedar"),
        },
        {
            "name": "external_viewer_view_floor",
            "description": "A non-internal viewer MUST be able to viewPresentation when inside campaign window.",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_externalViewerView.cedar"),
        },
        {
            "name": "internal_viewer_duplicate_floor",
            "description": "Internal viewers MUST be able to duplicatePresentation (exempt from campaign window).",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internalViewerDuplicate.cedar"),
        },
        {
            "name": "market_viewer_template_floor",
            "description": "Users in viewerMarkets MUST be able to viewTemplate.",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_marketViewerTemplate.cedar"),
        },
        {
            "name": "template_owner_edit_floor",
            "description": "Template owner MUST be able to editTemplate.",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_templateOwnerEdit.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantViewPresentation",
            "description": "grantViewAccessToPresentation policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditPresentation",
            "description": "grantEditAccessToPresentation policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantViewTemplate",
            "description": "grantViewAccessToTemplate policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantEditTemplate",
            "description": "grantEditAccessToTemplate policy is not trivially deny-all.",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
        },
    ]
