"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_reservation_ceiling",
            "description": "viewReservation only allowed if resource is in viewer, member, or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "update_reservation_ceiling",
            "description": "updateReservation only allowed if resource is in member or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grant_access_reservation_ceiling",
            "description": "grantAccessReservation only allowed if resource is in admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "create_reservation_ceiling",
            "description": "createReservation only allowed if resource is in member or admin permission sets, and loyalty tier restriction respected",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "view_property_ceiling",
            "description": "viewProperty only allowed if resource is in viewer, member, or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "update_property_ceiling",
            "description": "updateProperty only allowed if resource is in member or admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grant_access_property_ceiling",
            "description": "grantAccessProperty only allowed if resource is in admin permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "view_hotel_ceiling",
            "description": "viewHotel only allowed if resource is in viewer or member or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "update_hotel_ceiling",
            "description": "updateHotel only allowed if resource is in member or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "create_property_ceiling",
            "description": "createProperty only allowed if resource is in member or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "create_hotel_ceiling",
            "description": "createHotel only allowed if resource is in member or admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "grant_access_hotel_ceiling",
            "description": "grantAccessHotel only allowed if resource is in admin hotel permission sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "loyalty_tier_forbid_ceiling",
            "description": "createReservation on premium property with loyaltyTier < 3 must be denied",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "floor_viewer_reservation",
            "description": "A user with viewPermissions.hotelReservations covering the reservation MUST be able to viewReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewReservation_hotel.cedar"),
        },
        {
            "name": "floor_member_update_reservation",
            "description": "A user with memberPermissions.hotelReservations covering the reservation MUST be able to updateReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_updateReservation_member.cedar"),
        },
        {
            "name": "floor_admin_grant_reservation",
            "description": "A user with hotelAdminPermissions covering the reservation MUST be able to grantAccessReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_grantAccessReservation_admin.cedar"),
        },
        {
            "name": "floor_member_create_reservation_nonpremium",
            "description": "A member MUST be able to createReservation on a non-premium property",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_createReservation_nonpremium.cedar"),
        },
        {
            "name": "floor_member_create_reservation_premium_high_tier",
            "description": "A member with loyaltyTier >= 3 MUST be able to createReservation on a premium property",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_createReservation_premium_hightier.cedar"),
        },
        {
            "name": "floor_admin_grant_hotel",
            "description": "An admin MUST be able to grantAccessHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_grantAccessHotel_admin.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_createReservation",
            "description": "createReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_grantAccessHotel",
            "description": "grantAccessHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
        },
    ]
