"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_safety_ceiling",
            "description": "View is only permitted when projectStatus is Active, principal is ClinicalResearcher or PrincipalInvestigator with their respective constraints, department matches or principal is GlobalAuditor, and embargo is not active or principal is PI",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view.cedar"),
        },
        {
            "name": "edit_safety_ceiling",
            "description": "Edit is only permitted when projectStatus is Active, principal is ClinicalResearcher or PrincipalInvestigator with their respective constraints, department matches or principal is GlobalAuditor, and embargo is not active or principal is PI",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit.cedar"),
        },
        {
            "name": "active_project_gate_view",
            "description": "View is denied when projectStatus is not Active \u2014 no permit should fire for non-active projects",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_gate_view.cedar"),
        },
        {
            "name": "active_project_gate_edit",
            "description": "Edit is denied when projectStatus is not Active \u2014 no permit should fire for non-active projects",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_active_gate_edit.cedar"),
        },
        {
            "name": "cross_dept_block_view",
            "description": "View is forbidden when department != projectManagingDepartment unless principal is GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_view.cedar"),
        },
        {
            "name": "cross_dept_block_edit",
            "description": "Edit is forbidden when department != projectManagingDepartment unless principal is GlobalAuditor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_cross_dept_edit.cedar"),
        },
        {
            "name": "embargo_block_view",
            "description": "View is forbidden when requestTime < embargoUntil unless principal is PrincipalInvestigator",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_embargo_view.cedar"),
        },
        {
            "name": "embargo_block_edit",
            "description": "Edit is forbidden when requestTime < embargoUntil unless principal is PrincipalInvestigator",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_embargo_edit.cedar"),
        },
        {
            "name": "floor_clinical_researcher_view",
            "description": "A ClinicalResearcher with clearanceLevel > 3, matching department, on an Active non-HighlyRestricted non-embargoed document MUST be able to View",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_clinical_researcher_view.cedar"),
        },
        {
            "name": "floor_clinical_researcher_edit",
            "description": "A ClinicalResearcher with clearanceLevel > 3, matching department, on an Active non-HighlyRestricted non-embargoed document MUST be able to Edit",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_clinical_researcher_edit.cedar"),
        },
        {
            "name": "floor_pi_view",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, on an Active document MUST be able to View (even if embargoed, since PI is exempt)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_view.cedar"),
        },
        {
            "name": "floor_pi_edit",
            "description": "A PrincipalInvestigator with compliant device, low risk score, matching department, on an Active document MUST be able to Edit (even if embargoed, since PI is exempt)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_pi_edit.cedar"),
        },
        {
            "name": "floor_auditor_cross_dept_view",
            "description": "A GlobalAuditor who is also a ClinicalResearcher with clearanceLevel > 3, on an Active non-HighlyRestricted non-embargoed document in a different department MUST be able to View (auditor exemption from cross-dept block)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_auditor_cross_dept_view.cedar"),
        },
        {
            "name": "liveness_view",
            "description": "View policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"View\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit",
            "description": "Edit policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"Edit\"",
            "resource_type": "Document",
        },
    ]
