"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_presentation_safety",
            "description": "viewPresentation only allowed if principal is owner, in editors, or in viewers (with job=internal for InternalPrezViewActions path, or any job for ExternalPrezViewActions path)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_safety",
            "description": "duplicatePresentation only allowed if principal is owner, in editors, or (job=internal AND in viewers)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_safety",
            "description": "editPresentation only allowed if principal is owner or in editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "grant_view_presentation_safety",
            "description": "grantViewAccessToPresentation only if (owner or editor) AND (target is not customer OR (principal is distributor with same customerId))",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewPresentation.cedar"),
        },
        {
            "name": "grant_edit_presentation_safety",
            "description": "grantEditAccessToPresentation only if (owner or editor) AND target.job == internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditPresentation.cedar"),
        },
        {
            "name": "remove_self_presentation_safety",
            "description": "removeSelfAccessFromPresentation only if principal is owner, in editors, or in viewers (with internal for InternalPrezView, or any for ExternalPrezView)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfPresentation.cedar"),
        },
        {
            "name": "view_template_safety",
            "description": "viewTemplate only if owner, in editors, in editorMarkets, (internal AND in viewers), or in viewerMarkets; subject to unapproved restriction for non-internal on edit/market paths",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "duplicate_template_safety",
            "description": "duplicateTemplate only allowed via TemplateEditActions (owner/editor/editorMarket), InternalTemplateViewActions (internal+viewer), or MarketTemplateViewActions (viewerMarkets); unapproved restriction applies to non-internal on edit and market paths",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "edit_template_safety",
            "description": "editTemplate only if owner, in editors, or in editorMarkets; unapproved forbid blocks non-internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "grant_view_template_safety",
            "description": "grantViewAccessToTemplate only if (owner/editor/editorMarket) AND not forbidden by customer restriction AND not forbidden by unapproved restriction for non-internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_safety",
            "description": "grantEditAccessToTemplate only if (owner/editor/editorMarket) AND (no targetUser OR targetUser.job==internal) AND not forbidden by unapproved restriction for non-internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditTemplate.cedar"),
        },
        {
            "name": "remove_self_template_safety",
            "description": "removeSelfAccessFromTemplate only if owner, in editors, in editorMarkets (with approval gate for non-internal), or (internal AND in viewers)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfTemplate.cedar"),
        },
        {
            "name": "remove_others_template_safety",
            "description": "removeOthersAccessToTemplate only if owner, in editors, or in editorMarkets; unapproved forbid blocks non-internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersTemplate.cedar"),
        },
        {
            "name": "floor_external_viewer_view_presentation",
            "description": "A user in resource.viewers MUST be able to viewPresentation (external view path)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_externalViewerViewPres.cedar"),
        },
        {
            "name": "floor_owner_edit_presentation",
            "description": "The owner of a presentation MUST be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_ownerEditPres.cedar"),
        },
        {
            "name": "floor_internal_viewer_duplicate_presentation",
            "description": "An internal user in viewers MUST be able to duplicatePresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internalViewerDupPres.cedar"),
        },
        {
            "name": "floor_owner_view_template_approved",
            "description": "The owner of an approved template MUST be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_ownerViewTemplate.cedar"),
        },
        {
            "name": "floor_market_viewer_view_approved_template",
            "description": "A user in viewerMarkets MUST be able to viewTemplate on approved templates",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_marketViewerViewTemplate.cedar"),
        },
        {
            "name": "floor_internal_editor_unapproved_template",
            "description": "An internal user who is owner/editor/editorMarket MUST be able to editTemplate even on unapproved templates",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internalEditUnapproved.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_duplicatePresentation",
            "description": "duplicatePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantViewPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantViewTemplate",
            "description": "grantViewAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantEditTemplate",
            "description": "grantEditAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
        },
    ]
