"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_document_safety_user",
            "description": "User can ViewDocument only if: owner, in viewACL, in manageACL, or publicAccess is view/edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_user.cedar"),
        },
        {
            "name": "view_document_safety_public",
            "description": "Public can ViewDocument only if publicAccess is view or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_public.cedar"),
        },
        {
            "name": "modify_document_safety",
            "description": "User can ModifyDocument only if: owner, in modifyACL, or publicAccess is edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_document.cedar"),
        },
        {
            "name": "delete_document_safety",
            "description": "User can DeleteDocument only if: owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete_document.cedar"),
        },
        {
            "name": "edit_is_private_safety",
            "description": "User can EditIsPrivate only if: owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "edit_public_access_safety",
            "description": "User can EditPublicAccess only if: owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "add_to_share_acl_safety",
            "description": "User can AddToShareACL only if: owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "delete_group_safety",
            "description": "User can DeleteGroup only if they are the group owner and authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "modify_group_safety",
            "description": "User can ModifyGroup only if they are the group owner and authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "blocking_view_forbid",
            "description": "ViewDocument is denied when principal is in owner's blocked set (bidirectional blocking enforced)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_no_blocked.cedar"),
        },
        {
            "name": "blocking_modify_forbid",
            "description": "ModifyDocument is denied when principal is in owner's blocked set (bidirectional blocking enforced)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_no_blocked.cedar"),
        },
        {
            "name": "auth_required_view",
            "description": "User cannot ViewDocument without authentication",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_view.cedar"),
        },
        {
            "name": "auth_required_modify",
            "description": "User cannot ModifyDocument without authentication",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_modify.cedar"),
        },
        {
            "name": "auth_required_delete",
            "description": "User cannot DeleteDocument without authentication",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_delete.cedar"),
        },
        {
            "name": "org_isolation_view",
            "description": "User cannot ViewDocument cross-org unless in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_org_view.cedar"),
        },
        {
            "name": "org_isolation_modify",
            "description": "User cannot ModifyDocument cross-org unless in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_org_modify.cedar"),
        },
        {
            "name": "org_isolation_delete",
            "description": "User cannot DeleteDocument cross-org unless in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_org_delete.cedar"),
        },
        {
            "name": "org_isolation_add_share",
            "description": "User cannot AddToShareACL cross-org unless in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_org_add_share.cedar"),
        },
        {
            "name": "floor_owner_view",
            "description": "Owner MUST be able to ViewDocument when authenticated, same org, and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view.cedar"),
        },
        {
            "name": "floor_owner_modify",
            "description": "Owner MUST be able to ModifyDocument when authenticated, same org, and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify.cedar"),
        },
        {
            "name": "floor_owner_delete",
            "description": "Owner MUST be able to DeleteDocument when authenticated and same org",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete.cedar"),
        },
        {
            "name": "floor_view_acl",
            "description": "User in viewACL MUST be able to ViewDocument when authenticated, same org, and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl.cedar"),
        },
        {
            "name": "floor_modify_acl",
            "description": "User in modifyACL MUST be able to ModifyDocument when authenticated, same org, and not blocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl.cedar"),
        },
        {
            "name": "floor_manage_acl_delete",
            "description": "User in manageACL MUST be able to DeleteDocument when authenticated (manageACL bypasses org isolation)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_delete.cedar"),
        },
        {
            "name": "floor_public_view",
            "description": "Public principal MUST be able to ViewDocument when publicAccess is view",
            "type": "floor",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_public_view.cedar"),
        },
        {
            "name": "floor_group_owner_delete",
            "description": "Group owner MUST be able to DeleteGroup when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_delete.cedar"),
        },
        {
            "name": "liveness_view_document_user",
            "description": "ViewDocument for User is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document",
            "description": "ModifyDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_create_document",
            "description": "CreateDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
        },
    ]
