"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "owner_view_safety",
            "description": "ViewDocument for User principals is only allowed if owner, in viewACL, in manageACL, or publicAccess is view/edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_user_view.cedar"),
        },
        {
            "name": "modify_safety",
            "description": "ModifyDocument for User principals is only allowed if owner, in modifyACL, or publicAccess is edit",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_user_modify.cedar"),
        },
        {
            "name": "delete_safety",
            "description": "DeleteDocument is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete.cedar"),
        },
        {
            "name": "edit_is_private_safety",
            "description": "EditIsPrivate is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "edit_public_access_safety",
            "description": "EditPublicAccess is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "add_to_share_acl_safety",
            "description": "AddToShareACL is only allowed if owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "public_view_safety",
            "description": "ViewDocument for Public principals is only allowed if publicAccess is view or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_public_view.cedar"),
        },
        {
            "name": "delete_group_safety",
            "description": "DeleteGroup is only allowed if principal is the group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "modify_group_safety",
            "description": "ModifyGroup is only allowed if principal is the group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "auth_required_view",
            "description": "User principals cannot ViewDocument when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_view.cedar"),
        },
        {
            "name": "auth_required_modify",
            "description": "User principals cannot ModifyDocument when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_modify.cedar"),
        },
        {
            "name": "auth_required_delete",
            "description": "User principals cannot DeleteDocument when not authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_auth_delete.cedar"),
        },
        {
            "name": "owner_floor_view",
            "description": "Owner MUST be able to ViewDocument when authenticated and not blocked (or in manageACL)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view.cedar"),
        },
        {
            "name": "owner_floor_modify",
            "description": "Owner MUST be able to ModifyDocument when authenticated and not blocked (or in manageACL)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify.cedar"),
        },
        {
            "name": "owner_floor_delete",
            "description": "Owner MUST be able to DeleteDocument when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete.cedar"),
        },
        {
            "name": "view_acl_floor",
            "description": "Users in viewACL MUST be able to ViewDocument when authenticated (and in manageACL to bypass blocks)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl.cedar"),
        },
        {
            "name": "modify_acl_floor",
            "description": "Users in modifyACL MUST be able to ModifyDocument when authenticated (and in manageACL to bypass blocks)",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl.cedar"),
        },
        {
            "name": "manage_acl_floor_add_share",
            "description": "Users in manageACL MUST be able to AddToShareACL when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_add_share.cedar"),
        },
        {
            "name": "public_view_floor",
            "description": "Public principal MUST be able to ViewDocument when publicAccess is view",
            "type": "floor",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_public_view.cedar"),
        },
        {
            "name": "group_owner_floor_delete",
            "description": "Group owner MUST be able to DeleteGroup when authenticated",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_delete.cedar"),
        },
        {
            "name": "liveness_view_document",
            "description": "ViewDocument is not trivially deny-all for Users",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document",
            "description": "ModifyDocument is not trivially deny-all for Users",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_create_document",
            "description": "CreateDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_create_group",
            "description": "CreateGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_public_view",
            "description": "ViewDocument for Public is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
    ]
