"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "external_prez_view_safety",
            "description": "ExternalPrezViewActions on Presentation only if principal in resource.viewers OR principal in resource.viewerTeams OR resource.owner == principal OR principal in resource.editors OR principal in resource.editorTeams (since PrezEditActions is a superset containing these actions)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_safety",
            "description": "duplicatePresentation only if (internal AND in viewers) OR owner OR in editors OR in editorTeams",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_safety",
            "description": "editPresentation only if owner OR in editors OR in editorTeams",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "grant_view_prez_safety",
            "description": "grantViewAccessToPresentation only if (owner OR editors OR editorTeams) AND customer sharing restriction respected",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "grant_edit_prez_safety",
            "description": "grantEditAccessToPresentation only if (owner OR editors OR editorTeams) AND target is internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "remove_self_prez_safety",
            "description": "removeSelfAccessFromPresentation accessible via external view (viewers/viewerTeams), internal view (internal+viewers), or edit (owner/editors/editorTeams)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "view_template_safety",
            "description": "viewTemplate only if (in viewerMarkets) OR (internal AND in viewers) OR (owner OR editors OR editorMarkets)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "duplicate_template_safety",
            "description": "duplicateTemplate same as viewTemplate ceiling",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "edit_template_safety",
            "description": "editTemplate only if owner OR editors OR editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "grant_view_template_safety",
            "description": "grantViewAccessToTemplate only if (owner OR editors OR editorMarkets) AND customer restriction on targetUser",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_safety",
            "description": "grantEditAccessToTemplate only if (owner OR editors OR editorMarkets) AND targetUser must be internal if present",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "remove_self_template_safety",
            "description": "removeSelfAccessFromTemplate only if (internal AND in viewers) OR (owner OR editors OR editorMarkets)",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromTemplate.cedar"),
        },
        {
            "name": "remove_others_template_safety",
            "description": "removeOthersAccessToTemplate only if owner OR editors OR editorMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "floor_owner_edit_presentation",
            "description": "Presentation owner MUST be able to edit their presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_owner_editPresentation.cedar"),
        },
        {
            "name": "floor_viewer_viewPresentation",
            "description": "A user in resource.viewers MUST be able to view a presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_viewer_viewPresentation.cedar"),
        },
        {
            "name": "floor_viewerTeam_viewPresentation",
            "description": "A user in resource.viewerTeams MUST be able to view a presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_viewerTeam_viewPresentation.cedar"),
        },
        {
            "name": "floor_editorTeam_editPresentation",
            "description": "A user in resource.editorTeams MUST be able to edit a presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editorTeam_editPresentation.cedar"),
        },
        {
            "name": "floor_internal_viewer_duplicate",
            "description": "An internal user in resource.viewers MUST be able to duplicate a presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_viewer_duplicate.cedar"),
        },
        {
            "name": "floor_market_viewTemplate",
            "description": "A user in resource.viewerMarkets MUST be able to view a template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_market_viewTemplate.cedar"),
        },
        {
            "name": "floor_owner_editTemplate",
            "description": "Template owner MUST be able to edit their template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_owner_editTemplate.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
    ]
