"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "viewReservation_ceiling",
            "description": "viewReservation is only allowed if resource is reachable via viewPermissions, memberPermissions, or admin permissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "updateReservation_ceiling",
            "description": "updateReservation is only allowed via memberPermissions or admin permissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "grantAccessReservation_ceiling",
            "description": "grantAccessReservation is only allowed via admin permissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "createReservation_ceiling",
            "description": "createReservation on a Property is only allowed via memberPermissions or admin permissions, and blocked by renovation unless admin",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "viewProperty_ceiling",
            "description": "viewProperty is only allowed via viewPermissions, memberPermissions, or admin permissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "updateProperty_ceiling",
            "description": "updateProperty is only allowed via memberPermissions or admin permissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "grantAccessProperty_ceiling",
            "description": "grantAccessProperty is only allowed via admin permissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "viewHotel_ceiling",
            "description": "viewHotel is only allowed via viewPermissions.hotelReservations, memberPermissions.hotelReservations, or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "updateHotel_ceiling",
            "description": "updateHotel is only allowed via memberPermissions.hotelReservations or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "createProperty_ceiling",
            "description": "createProperty on a Hotel is only allowed via memberPermissions.hotelReservations or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "createHotel_ceiling",
            "description": "createHotel is only allowed via memberPermissions.hotelReservations or hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "grantAccessHotel_ceiling",
            "description": "grantAccessHotel is only allowed via hotelAdminPermissions",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "renovation_forbid_ceiling",
            "description": "createReservation must be forbidden on renovating properties for non-admin users",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "floor_viewer_viewReservation",
            "description": "Users with viewPermissions for a reservation's hotel MUST be able to view that reservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewer_viewReservation.cedar"),
        },
        {
            "name": "floor_member_updateReservation",
            "description": "Users with memberPermissions for a reservation's hotel MUST be able to update that reservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_member_updateReservation.cedar"),
        },
        {
            "name": "floor_admin_grantAccessReservation",
            "description": "Users with admin permissions for a reservation's hotel MUST be able to grant access on that reservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessReservation.cedar"),
        },
        {
            "name": "floor_member_createReservation",
            "description": "Members MUST be able to createReservation on non-renovating properties",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_member_createReservation.cedar"),
        },
        {
            "name": "floor_admin_createReservation_renovation",
            "description": "Admins MUST be able to createReservation even on renovating properties",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_admin_createReservation_renovation.cedar"),
        },
        {
            "name": "floor_admin_grantAccessHotel",
            "description": "Hotel admins MUST be able to grant access on hotels in their admin set",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_admin_grantAccessHotel.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_updateReservation",
            "description": "updateReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_createReservation",
            "description": "createReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_viewProperty",
            "description": "viewProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewHotel",
            "description": "viewHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_grantAccessHotel",
            "description": "grantAccessHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
        },
    ]
