"""Auto-generated verification plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "owner_view_safety",
            "description": "ViewDocument for User principals is only allowed if: owner, in viewACL, in modifyACL (not needed but checking ceiling), in manageACL, or publicAccess allows it \u2014 and not blocked and authenticated",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_user.cedar"),
        },
        {
            "name": "public_view_safety",
            "description": "ViewDocument for Public principals is only allowed if publicAccess is view or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_public.cedar"),
        },
        {
            "name": "modify_safety",
            "description": "ModifyDocument is only allowed for authenticated users who are owner or in modifyACL or publicAccess==edit, not blocked, and document is not locked",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify.cedar"),
        },
        {
            "name": "delete_safety",
            "description": "DeleteDocument is only allowed for authenticated users who are owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete.cedar"),
        },
        {
            "name": "edit_is_private_safety",
            "description": "EditIsPrivate is only allowed for authenticated users who are owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "edit_public_access_safety",
            "description": "EditPublicAccess is only allowed for authenticated users who are owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "add_to_share_acl_safety",
            "description": "AddToShareACL is only allowed for authenticated users who are owner or in manageACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "delete_group_safety",
            "description": "DeleteGroup is only allowed for authenticated users who are the group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group.cedar"),
        },
        {
            "name": "modify_group_safety",
            "description": "ModifyGroup is only allowed for authenticated users who are the group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group.cedar"),
        },
        {
            "name": "owner_view_floor",
            "description": "Owner who is authenticated and not blocked MUST be able to ViewDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view.cedar"),
        },
        {
            "name": "owner_modify_floor",
            "description": "Owner who is authenticated and not blocked and doc not locked MUST be able to ModifyDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify.cedar"),
        },
        {
            "name": "owner_delete_floor",
            "description": "Owner who is authenticated MUST be able to DeleteDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete.cedar"),
        },
        {
            "name": "view_acl_floor",
            "description": "User in viewACL who is authenticated and not blocked MUST be able to ViewDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl.cedar"),
        },
        {
            "name": "modify_acl_floor",
            "description": "User in modifyACL who is authenticated and not blocked and doc not locked MUST be able to ModifyDocument",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl.cedar"),
        },
        {
            "name": "manage_acl_add_share_floor",
            "description": "User in manageACL who is authenticated MUST be able to AddToShareACL",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_add_share.cedar"),
        },
        {
            "name": "public_view_floor",
            "description": "Public principal MUST be able to ViewDocument when publicAccess==view",
            "type": "floor",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_public_view.cedar"),
        },
        {
            "name": "group_owner_delete_floor",
            "description": "Group owner who is authenticated MUST be able to DeleteGroup",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_group_owner_delete.cedar"),
        },
        {
            "name": "locked_doc_blocks_modify",
            "description": "ModifyDocument must be denied when document is locked, even for owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_locked.cedar"),
        },
        {
            "name": "liveness_view_document",
            "description": "ViewDocument policy is not trivially deny-all for Users",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document",
            "description": "ModifyDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_modify_group",
            "description": "ModifyGroup policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_view_public",
            "description": "ViewDocument policy is not trivially deny-all for Public",
            "type": "always-denies-liveness",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
    ]
